/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblAtagAbnote;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtagAbnoteJQR extends UpdatableRecordImpl<AtagAbnoteJQR> implements Record4<Long, String, String, Integer> {

	private static final long serialVersionUID = 1242780851;

	/**
	 * Setter for <code>mic_core.atag_abnote.atag_id</code>.
	 */
	public void setAtagId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.atag_abnote.atag_id</code>.
	 */
	public Long getAtagId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.atag_abnote.atag_value</code>.
	 */
	public void setAtagValue(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.atag_abnote.atag_value</code>.
	 */
	public String getAtagValue() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.atag_abnote.seo_url</code>.
	 */
	public void setSeoUrl(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.atag_abnote.seo_url</code>.
	 */
	public String getSeoUrl() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.atag_abnote.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.atag_abnote.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, String, String, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, String, String, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblAtagAbnote.ATAG_ABNOTE.ATAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TblAtagAbnote.ATAG_ABNOTE.ATAG_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblAtagAbnote.ATAG_ABNOTE.SEO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TblAtagAbnote.ATAG_ABNOTE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAtagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAtagValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSeoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AtagAbnoteJQR value1(Long value) {
		setAtagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AtagAbnoteJQR value2(String value) {
		setAtagValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AtagAbnoteJQR value3(String value) {
		setSeoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AtagAbnoteJQR value4(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AtagAbnoteJQR values(Long value1, String value2, String value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AtagAbnoteJQR
	 */
	public AtagAbnoteJQR() {
		super(TblAtagAbnote.ATAG_ABNOTE);
	}

	/**
	 * Create a detached, initialised AtagAbnoteJQR
	 */
	public AtagAbnoteJQR(Long atagId, String atagValue, String seoUrl, Integer lastUpdMictime) {
		super(TblAtagAbnote.ATAG_ABNOTE);

		setValue(0, atagId);
		setValue(1, atagValue);
		setValue(2, seoUrl);
		setValue(3, lastUpdMictime);
	}
}
