/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblAttrAbvintage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttrAbvintageJQR extends UpdatableRecordImpl<AttrAbvintageJQR> implements Record7<Long, Short, String, String, String, Boolean, Integer> {

	private static final long serialVersionUID = -1652993448;

	/**
	 * Setter for <code>mic_core.attr_abvintage.attr_id</code>.
	 */
	public void setAttrId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.attr_id</code>.
	 */
	public Long getAttrId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.attr_name_id</code>.
	 */
	public void setAttrNameId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.attr_name_id</code>.
	 */
	public Short getAttrNameId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.attr_val_eng</code>.
	 */
	public void setAttrValEng(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.attr_val_eng</code>.
	 */
	public String getAttrValEng() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.attr_val_chs</code>.
	 */
	public void setAttrValChs(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.attr_val_chs</code>.
	 */
	public String getAttrValChs() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.attr_val_cht</code>.
	 */
	public void setAttrValCht(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.attr_val_cht</code>.
	 */
	public String getAttrValCht() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.is_valid</code>.
	 */
	public void setIsValid(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.is_valid</code>.
	 */
	public Boolean getIsValid() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.attr_abvintage.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abvintage.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Short, String, String, String, Boolean, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Short, String, String, String, Boolean, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.ATTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.ATTR_NAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.ATTR_VAL_ENG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.ATTR_VAL_CHS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.ATTR_VAL_CHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.IS_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return TblAttrAbvintage.ATTR_ABVINTAGE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAttrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getAttrNameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAttrValEng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAttrValChs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAttrValCht();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value1(Long value) {
		setAttrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value2(Short value) {
		setAttrNameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value3(String value) {
		setAttrValEng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value4(String value) {
		setAttrValChs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value5(String value) {
		setAttrValCht(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value6(Boolean value) {
		setIsValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR value7(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbvintageJQR values(Long value1, Short value2, String value3, String value4, String value5, Boolean value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttrAbvintageJQR
	 */
	public AttrAbvintageJQR() {
		super(TblAttrAbvintage.ATTR_ABVINTAGE);
	}

	/**
	 * Create a detached, initialised AttrAbvintageJQR
	 */
	public AttrAbvintageJQR(Long attrId, Short attrNameId, String attrValEng, String attrValChs, String attrValCht, Boolean isValid, Integer lastUpdMictime) {
		super(TblAttrAbvintage.ATTR_ABVINTAGE);

		setValue(0, attrId);
		setValue(1, attrNameId);
		setValue(2, attrValEng);
		setValue(3, attrValChs);
		setValue(4, attrValCht);
		setValue(5, isValid);
		setValue(6, lastUpdMictime);
	}
}
