/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblAttrAbnote;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttrAbnoteJQR extends UpdatableRecordImpl<AttrAbnoteJQR> implements Record8<Long, Short, String, String, String, String, Boolean, Integer> {

	private static final long serialVersionUID = -532138482;

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_id</code>.
	 */
	public void setAttrId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_id</code>.
	 */
	public Long getAttrId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_name_id</code>.
	 */
	public void setAttrNameId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_name_id</code>.
	 */
	public Short getAttrNameId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_val_usr</code>.
	 */
	public void setAttrValUsr(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_val_usr</code>.
	 */
	public String getAttrValUsr() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_val_eng</code>.
	 */
	public void setAttrValEng(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_val_eng</code>.
	 */
	public String getAttrValEng() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_val_chs</code>.
	 */
	public void setAttrValChs(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_val_chs</code>.
	 */
	public String getAttrValChs() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.attr_val_cht</code>.
	 */
	public void setAttrValCht(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.attr_val_cht</code>.
	 */
	public String getAttrValCht() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.is_valid</code>.
	 */
	public void setIsValid(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.is_valid</code>.
	 */
	public Boolean getIsValid() {
		return (Boolean) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.attr_abnote.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.attr_abnote.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Short, String, String, String, String, Boolean, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Short, String, String, String, String, Boolean, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_NAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_VAL_USR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_VAL_ENG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_VAL_CHS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblAttrAbnote.ATTR_ABNOTE.ATTR_VAL_CHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return TblAttrAbnote.ATTR_ABNOTE.IS_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return TblAttrAbnote.ATTR_ABNOTE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAttrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getAttrNameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAttrValUsr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAttrValEng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAttrValChs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAttrValCht();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getIsValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value1(Long value) {
		setAttrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value2(Short value) {
		setAttrNameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value3(String value) {
		setAttrValUsr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value4(String value) {
		setAttrValEng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value5(String value) {
		setAttrValChs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value6(String value) {
		setAttrValCht(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value7(Boolean value) {
		setIsValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR value8(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttrAbnoteJQR values(Long value1, Short value2, String value3, String value4, String value5, String value6, Boolean value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttrAbnoteJQR
	 */
	public AttrAbnoteJQR() {
		super(TblAttrAbnote.ATTR_ABNOTE);
	}

	/**
	 * Create a detached, initialised AttrAbnoteJQR
	 */
	public AttrAbnoteJQR(Long attrId, Short attrNameId, String attrValUsr, String attrValEng, String attrValChs, String attrValCht, Boolean isValid, Integer lastUpdMictime) {
		super(TblAttrAbnote.ATTR_ABNOTE);

		setValue(0, attrId);
		setValue(1, attrNameId);
		setValue(2, attrValUsr);
		setValue(3, attrValEng);
		setValue(4, attrValChs);
		setValue(5, attrValCht);
		setValue(6, isValid);
		setValue(7, lastUpdMictime);
	}
}
