/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblPlace;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceJQR extends UpdatableRecordImpl<PlaceJQR> implements Record5<Long, String, UUID, Boolean, Integer> {

	private static final long serialVersionUID = -1290346344;

	/**
	 * Setter for <code>mic_core.place.place_id</code>.
	 */
	public void setPlaceId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.place.place_id</code>.
	 */
	public Long getPlaceId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.place.place_name</code>.
	 */
	public void setPlaceName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.place.place_name</code>.
	 */
	public String getPlaceName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.place.place_name_hash</code>.
	 */
	public void setPlaceNameHash(UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.place.place_name_hash</code>.
	 */
	public UUID getPlaceNameHash() {
		return (UUID) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.place.is_archived</code>.
	 */
	public void setIsArchived(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.place.is_archived</code>.
	 */
	public Boolean getIsArchived() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.place.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.place.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, UUID, Boolean, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, UUID, Boolean, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblPlace.PLACE.PLACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TblPlace.PLACE.PLACE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field3() {
		return TblPlace.PLACE.PLACE_NAME_HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return TblPlace.PLACE.IS_ARCHIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TblPlace.PLACE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getPlaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPlaceName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value3() {
		return getPlaceNameHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getIsArchived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR value1(Long value) {
		setPlaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR value2(String value) {
		setPlaceName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR value3(UUID value) {
		setPlaceNameHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR value4(Boolean value) {
		setIsArchived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR value5(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlaceJQR values(Long value1, String value2, UUID value3, Boolean value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaceJQR
	 */
	public PlaceJQR() {
		super(TblPlace.PLACE);
	}

	/**
	 * Create a detached, initialised PlaceJQR
	 */
	public PlaceJQR(Long placeId, String placeName, UUID placeNameHash, Boolean isArchived, Integer lastUpdMictime) {
		super(TblPlace.PLACE);

		setValue(0, placeId);
		setValue(1, placeName);
		setValue(2, placeNameHash);
		setValue(3, isArchived);
		setValue(4, lastUpdMictime);
	}
}
