/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblUauthSclntw;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UauthSclntwJQR extends UpdatableRecordImpl<UauthSclntwJQR> implements Record16<UUID, Short, String, String, String, String, String, String, Short, String, String, String, String, String, String, Timestamp> {

	private static final long serialVersionUID = -1086772143;

	/**
	 * Setter for <code>mic_core.uauth_sclntw.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_type</code>.
	 */
	public void setSnType(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_type</code>.
	 */
	public Short getSnType() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_userid</code>.
	 */
	public void setSnUserid(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_userid</code>.
	 */
	public String getSnUserid() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_token</code>.
	 */
	public void setSnToken(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_token</code>.
	 */
	public String getSnToken() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_name</code>.
	 */
	public void setSnName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_name</code>.
	 */
	public String getSnName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_firstname</code>.
	 */
	public void setSnFirstname(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_firstname</code>.
	 */
	public String getSnFirstname() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_lastname</code>.
	 */
	public void setSnLastname(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_lastname</code>.
	 */
	public String getSnLastname() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_gender</code>.
	 */
	public void setSnGender(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_gender</code>.
	 */
	public String getSnGender() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_timezone</code>.
	 */
	public void setSnTimezone(Short value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_timezone</code>.
	 */
	public Short getSnTimezone() {
		return (Short) getValue(8);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_locale</code>.
	 */
	public void setSnLocale(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_locale</code>.
	 */
	public String getSnLocale() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_link</code>.
	 */
	public void setSnLink(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_link</code>.
	 */
	public String getSnLink() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_email</code>.
	 */
	public void setSnEmail(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_email</code>.
	 */
	public String getSnEmail() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_birthday</code>.
	 */
	public void setSnBirthday(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_birthday</code>.
	 */
	public String getSnBirthday() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_about</code>.
	 */
	public void setSnAbout(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_about</code>.
	 */
	public String getSnAbout() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.sn_error</code>.
	 */
	public void setSnError(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.sn_error</code>.
	 */
	public String getSnError() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>mic_core.uauth_sclntw.last_upd_time</code>.
	 */
	public void setLastUpdTime(Timestamp value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_sclntw.last_upd_time</code>.
	 */
	public Timestamp getLastUpdTime() {
		return (Timestamp) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<UUID, Short, String, String, String, String, String, String, Short, String, String, String, String, String, String, Timestamp> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<UUID, Short, String, String, String, String, String, String, Short, String, String, String, String, String, String, Timestamp> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblUauthSclntw.UAUTH_SCLNTW.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_LASTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field9() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_TIMEZONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_BIRTHDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_ABOUT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return TblUauthSclntw.UAUTH_SCLNTW.SN_ERROR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field16() {
		return TblUauthSclntw.UAUTH_SCLNTW.LAST_UPD_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getSnType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSnUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSnToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSnName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSnFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSnLastname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSnGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value9() {
		return getSnTimezone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSnLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getSnLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getSnEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getSnBirthday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getSnAbout();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getSnError();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value16() {
		return getLastUpdTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value2(Short value) {
		setSnType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value3(String value) {
		setSnUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value4(String value) {
		setSnToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value5(String value) {
		setSnName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value6(String value) {
		setSnFirstname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value7(String value) {
		setSnLastname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value8(String value) {
		setSnGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value9(Short value) {
		setSnTimezone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value10(String value) {
		setSnLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value11(String value) {
		setSnLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value12(String value) {
		setSnEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value13(String value) {
		setSnBirthday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value14(String value) {
		setSnAbout(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value15(String value) {
		setSnError(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR value16(Timestamp value) {
		setLastUpdTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSclntwJQR values(UUID value1, Short value2, String value3, String value4, String value5, String value6, String value7, String value8, Short value9, String value10, String value11, String value12, String value13, String value14, String value15, Timestamp value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UauthSclntwJQR
	 */
	public UauthSclntwJQR() {
		super(TblUauthSclntw.UAUTH_SCLNTW);
	}

	/**
	 * Create a detached, initialised UauthSclntwJQR
	 */
	public UauthSclntwJQR(UUID userId, Short snType, String snUserid, String snToken, String snName, String snFirstname, String snLastname, String snGender, Short snTimezone, String snLocale, String snLink, String snEmail, String snBirthday, String snAbout, String snError, Timestamp lastUpdTime) {
		super(TblUauthSclntw.UAUTH_SCLNTW);

		setValue(0, userId);
		setValue(1, snType);
		setValue(2, snUserid);
		setValue(3, snToken);
		setValue(4, snName);
		setValue(5, snFirstname);
		setValue(6, snLastname);
		setValue(7, snGender);
		setValue(8, snTimezone);
		setValue(9, snLocale);
		setValue(10, snLink);
		setValue(11, snEmail);
		setValue(12, snBirthday);
		setValue(13, snAbout);
		setValue(14, snError);
		setValue(15, lastUpdTime);
	}
}
