/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUauthSimple;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UauthSimpleJQR extends UpdatableRecordImpl<UauthSimpleJQR> implements Record5<UUID, String, String, String, Integer> {

	private static final long serialVersionUID = 1747208242;

	/**
	 * Setter for <code>mic_core.uauth_simple.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_simple.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.uauth_simple.login_email</code>.
	 */
	public void setLoginEmail(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_simple.login_email</code>.
	 */
	public String getLoginEmail() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.uauth_simple.pwd_hash</code>.
	 */
	public void setPwdHash(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_simple.pwd_hash</code>.
	 */
	public String getPwdHash() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.uauth_simple.tlas</code>.
	 */
	public void setTlas(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_simple.tlas</code>.
	 */
	public String getTlas() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.uauth_simple.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.uauth_simple.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, String, String, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, String, String, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblUauthSimple.UAUTH_SIMPLE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TblUauthSimple.UAUTH_SIMPLE.LOGIN_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblUauthSimple.UAUTH_SIMPLE.PWD_HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblUauthSimple.UAUTH_SIMPLE.TLAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TblUauthSimple.UAUTH_SIMPLE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLoginEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPwdHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTlas();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR value2(String value) {
		setLoginEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR value3(String value) {
		setPwdHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR value4(String value) {
		setTlas(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR value5(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UauthSimpleJQR values(UUID value1, String value2, String value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UauthSimpleJQR
	 */
	public UauthSimpleJQR() {
		super(TblUauthSimple.UAUTH_SIMPLE);
	}

	/**
	 * Create a detached, initialised UauthSimpleJQR
	 */
	public UauthSimpleJQR(UUID userId, String loginEmail, String pwdHash, String tlas, Integer lastUpdMictime) {
		super(TblUauthSimple.UAUTH_SIMPLE);

		setValue(0, userId);
		setValue(1, loginEmail);
		setValue(2, pwdHash);
		setValue(3, tlas);
		setValue(4, lastUpdMictime);
	}
}
