/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUserFavWine;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavWineJQR extends UpdatableRecordImpl<UserFavWineJQR> implements Record5<UUID, Long, Short, Boolean, Integer> {

	private static final long serialVersionUID = 1501329547;

	/**
	 * Setter for <code>mic_core.user_fav_wine.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_fav_wine.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_fav_wine.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_fav_wine.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_fav_wine.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_fav_wine.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.user_fav_wine.is_archived</code>.
	 */
	public void setIsArchived(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.user_fav_wine.is_archived</code>.
	 */
	public Boolean getIsArchived() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.user_fav_wine.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.user_fav_wine.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<UUID, Long, Short> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, Long, Short, Boolean, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, Long, Short, Boolean, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblUserFavWine.USER_FAV_WINE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblUserFavWine.USER_FAV_WINE.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblUserFavWine.USER_FAV_WINE.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return TblUserFavWine.USER_FAV_WINE.IS_ARCHIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TblUserFavWine.USER_FAV_WINE.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getIsArchived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR value2(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR value3(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR value4(Boolean value) {
		setIsArchived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR value5(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserFavWineJQR values(UUID value1, Long value2, Short value3, Boolean value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserFavWineJQR
	 */
	public UserFavWineJQR() {
		super(TblUserFavWine.USER_FAV_WINE);
	}

	/**
	 * Create a detached, initialised UserFavWineJQR
	 */
	public UserFavWineJQR(UUID userId, Long wineId, Short vintageTag, Boolean isArchived, Integer lastUpdMictime) {
		super(TblUserFavWine.USER_FAV_WINE);

		setValue(0, userId);
		setValue(1, wineId);
		setValue(2, vintageTag);
		setValue(3, isArchived);
		setValue(4, lastUpdMictime);
	}
}
