/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUserOccasWith;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOccasWithJQR extends UpdatableRecordImpl<UserOccasWithJQR> implements Record2<Long, UUID> {

	private static final long serialVersionUID = 134019044;

	/**
	 * Setter for <code>mic_core.user_occas_with.occas_id</code>.
	 */
	public void setOccasId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas_with.occas_id</code>.
	 */
	public Long getOccasId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_occas_with.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas_with.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, UUID> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, UUID> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, UUID> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserOccasWith.USER_OCCAS_WITH.OCCAS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return TblUserOccasWith.USER_OCCAS_WITH.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getOccasId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasWithJQR value1(Long value) {
		setOccasId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasWithJQR value2(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasWithJQR values(Long value1, UUID value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserOccasWithJQR
	 */
	public UserOccasWithJQR() {
		super(TblUserOccasWith.USER_OCCAS_WITH);
	}

	/**
	 * Create a detached, initialised UserOccasWithJQR
	 */
	public UserOccasWithJQR(Long occasId, UUID userId) {
		super(TblUserOccasWith.USER_OCCAS_WITH);

		setValue(0, occasId);
		setValue(1, userId);
	}
}
