/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblUserNoteAtag;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNoteAtagJQR extends TableRecordImpl<UserNoteAtagJQR> implements Record3<Long, Long, Integer> {

	private static final long serialVersionUID = 2071727025;

	/**
	 * Setter for <code>mic_core.user_note_atag.note_id</code>.
	 */
	public void setNoteId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_atag.note_id</code>.
	 */
	public Long getNoteId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_note_atag.atag_id</code>.
	 */
	public void setAtagId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_atag.atag_id</code>.
	 */
	public Long getAtagId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_note_atag.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_atag.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Long, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserNoteAtag.USER_NOTE_ATAG.NOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblUserNoteAtag.USER_NOTE_ATAG.ATAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TblUserNoteAtag.USER_NOTE_ATAG.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getNoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getAtagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAtagJQR value1(Long value) {
		setNoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAtagJQR value2(Long value) {
		setAtagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAtagJQR value3(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAtagJQR values(Long value1, Long value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserNoteAtagJQR
	 */
	public UserNoteAtagJQR() {
		super(TblUserNoteAtag.USER_NOTE_ATAG);
	}

	/**
	 * Create a detached, initialised UserNoteAtagJQR
	 */
	public UserNoteAtagJQR(Long noteId, Long atagId, Integer lastUpdMictime) {
		super(TblUserNoteAtag.USER_NOTE_ATAG);

		setValue(0, noteId);
		setValue(1, atagId);
		setValue(2, lastUpdMictime);
	}
}
