/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUserDlvrProf;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDlvrProfJQR extends UpdatableRecordImpl<UserDlvrProfJQR> implements Record9<Long, UUID, String, String, String, String, String, String, Integer> {

	private static final long serialVersionUID = -243756140;

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.dlvr_id</code>.
	 */
	public void setDlvrId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.dlvr_id</code>.
	 */
	public Long getDlvrId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.is_default</code>.
	 */
	public void setIsDefault(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.is_default</code>.
	 */
	public String getIsDefault() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.firstname</code>.
	 */
	public void setFirstname(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.firstname</code>.
	 */
	public String getFirstname() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.lastname</code>.
	 */
	public void setLastname(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.lastname</code>.
	 */
	public String getLastname() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.address</code>.
	 */
	public void setAddress(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.country</code>.
	 */
	public void setCountry(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.country</code>.
	 */
	public String getCountry() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.contact_tel</code>.
	 */
	public void setContactTel(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.contact_tel</code>.
	 */
	public String getContactTel() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>mic_core.user_dlvr_prof.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mic_core.user_dlvr_prof.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Long, UUID, String, String, String, String, String, String, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Long, UUID, String, String, String, String, String, String, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserDlvrProf.USER_DLVR_PROF.DLVR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return TblUserDlvrProf.USER_DLVR_PROF.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblUserDlvrProf.USER_DLVR_PROF.IS_DEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblUserDlvrProf.USER_DLVR_PROF.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblUserDlvrProf.USER_DLVR_PROF.LASTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblUserDlvrProf.USER_DLVR_PROF.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblUserDlvrProf.USER_DLVR_PROF.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TblUserDlvrProf.USER_DLVR_PROF.CONTACT_TEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return TblUserDlvrProf.USER_DLVR_PROF.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getDlvrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getIsDefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getLastname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getContactTel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value1(Long value) {
		setDlvrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value2(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value3(String value) {
		setIsDefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value4(String value) {
		setFirstname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value5(String value) {
		setLastname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value6(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value7(String value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value8(String value) {
		setContactTel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR value9(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserDlvrProfJQR values(Long value1, UUID value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserDlvrProfJQR
	 */
	public UserDlvrProfJQR() {
		super(TblUserDlvrProf.USER_DLVR_PROF);
	}

	/**
	 * Create a detached, initialised UserDlvrProfJQR
	 */
	public UserDlvrProfJQR(Long dlvrId, UUID userId, String isDefault, String firstname, String lastname, String address, String country, String contactTel, Integer lastUpdMictime) {
		super(TblUserDlvrProf.USER_DLVR_PROF);

		setValue(0, dlvrId);
		setValue(1, userId);
		setValue(2, isDefault);
		setValue(3, firstname);
		setValue(4, lastname);
		setValue(5, address);
		setValue(6, country);
		setValue(7, contactTel);
		setValue(8, lastUpdMictime);
	}
}
