/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Date;
import java.util.UUID;

import myicellar.jooq.tables.TblUserOccas;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserOccasJQR extends UpdatableRecordImpl<UserOccasJQR> implements Record8<Long, UUID, Long, Date, String, Boolean, String, Integer> {

	private static final long serialVersionUID = 345978229;

	/**
	 * Setter for <code>mic_core.user_occas.occas_id</code>.
	 */
	public void setOccasId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.occas_id</code>.
	 */
	public Long getOccasId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_occas.host_user_id</code>.
	 */
	public void setHostUserId(UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.host_user_id</code>.
	 */
	public UUID getHostUserId() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_occas.host_place_id</code>.
	 */
	public void setHostPlaceId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.host_place_id</code>.
	 */
	public Long getHostPlaceId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.user_occas.occas_date</code>.
	 */
	public void setOccasDate(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.occas_date</code>.
	 */
	public Date getOccasDate() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.user_occas.occas_tag</code>.
	 */
	public void setOccasTag(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.occas_tag</code>.
	 */
	public String getOccasTag() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.user_occas.is_archived</code>.
	 */
	public void setIsArchived(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.is_archived</code>.
	 */
	public Boolean getIsArchived() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.user_occas.seo_url</code>.
	 */
	public void setSeoUrl(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.seo_url</code>.
	 */
	public String getSeoUrl() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.user_occas.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.user_occas.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, UUID, Long, Date, String, Boolean, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, UUID, Long, Date, String, Boolean, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserOccas.USER_OCCAS.OCCAS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return TblUserOccas.USER_OCCAS.HOST_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return TblUserOccas.USER_OCCAS.HOST_PLACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return TblUserOccas.USER_OCCAS.OCCAS_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblUserOccas.USER_OCCAS.OCCAS_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TblUserOccas.USER_OCCAS.IS_ARCHIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblUserOccas.USER_OCCAS.SEO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return TblUserOccas.USER_OCCAS.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getOccasId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getHostUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getHostPlaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getOccasDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getOccasTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsArchived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSeoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value1(Long value) {
		setOccasId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value2(UUID value) {
		setHostUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value3(Long value) {
		setHostPlaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value4(Date value) {
		setOccasDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value5(String value) {
		setOccasTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value6(Boolean value) {
		setIsArchived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value7(String value) {
		setSeoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR value8(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserOccasJQR values(Long value1, UUID value2, Long value3, Date value4, String value5, Boolean value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserOccasJQR
	 */
	public UserOccasJQR() {
		super(TblUserOccas.USER_OCCAS);
	}

	/**
	 * Create a detached, initialised UserOccasJQR
	 */
	public UserOccasJQR(Long occasId, UUID hostUserId, Long hostPlaceId, Date occasDate, String occasTag, Boolean isArchived, String seoUrl, Integer lastUpdMictime) {
		super(TblUserOccas.USER_OCCAS);

		setValue(0, occasId);
		setValue(1, hostUserId);
		setValue(2, hostPlaceId);
		setValue(3, occasDate);
		setValue(4, occasTag);
		setValue(5, isArchived);
		setValue(6, seoUrl);
		setValue(7, lastUpdMictime);
	}
}
