/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblUserNoteAttr;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNoteAttrJQR extends UpdatableRecordImpl<UserNoteAttrJQR> implements Record4<Long, Long, Short, Integer> {

	private static final long serialVersionUID = -484881109;

	/**
	 * Setter for <code>mic_core.user_note_attr.note_id</code>.
	 */
	public void setNoteId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_attr.note_id</code>.
	 */
	public Long getNoteId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_note_attr.attr_id</code>.
	 */
	public void setAttrId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_attr.attr_id</code>.
	 */
	public Long getAttrId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_note_attr.attr_assoc_val</code>.
	 */
	public void setAttrAssocVal(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_attr.attr_assoc_val</code>.
	 */
	public Short getAttrAssocVal() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.user_note_attr.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_attr.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Short, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Short, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserNoteAttr.USER_NOTE_ATTR.NOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblUserNoteAttr.USER_NOTE_ATTR.ATTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblUserNoteAttr.USER_NOTE_ATTR.ATTR_ASSOC_VAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TblUserNoteAttr.USER_NOTE_ATTR.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getNoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getAttrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getAttrAssocVal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAttrJQR value1(Long value) {
		setNoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAttrJQR value2(Long value) {
		setAttrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAttrJQR value3(Short value) {
		setAttrAssocVal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAttrJQR value4(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteAttrJQR values(Long value1, Long value2, Short value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserNoteAttrJQR
	 */
	public UserNoteAttrJQR() {
		super(TblUserNoteAttr.USER_NOTE_ATTR);
	}

	/**
	 * Create a detached, initialised UserNoteAttrJQR
	 */
	public UserNoteAttrJQR(Long noteId, Long attrId, Short attrAssocVal, Integer lastUpdMictime) {
		super(TblUserNoteAttr.USER_NOTE_ATTR);

		setValue(0, noteId);
		setValue(1, attrId);
		setValue(2, attrAssocVal);
		setValue(3, lastUpdMictime);
	}
}
