/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUserHeader;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHeaderJQR extends UpdatableRecordImpl<UserHeaderJQR> implements Record3<UUID, String, UUID> {

	private static final long serialVersionUID = 411369248;

	/**
	 * Setter for <code>mic_core.user_header.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_header.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_header.user_name</code>.
	 */
	public void setUserName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_header.user_name</code>.
	 */
	public String getUserName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_header.avatar_img</code>.
	 */
	public void setAvatarImg(UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_header.avatar_img</code>.
	 */
	public UUID getAvatarImg() {
		return (UUID) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, String, UUID> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, String, UUID> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblUserHeader.USER_HEADER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TblUserHeader.USER_HEADER.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field3() {
		return TblUserHeader.USER_HEADER.AVATAR_IMG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value3() {
		return getAvatarImg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserHeaderJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserHeaderJQR value2(String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserHeaderJQR value3(UUID value) {
		setAvatarImg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserHeaderJQR values(UUID value1, String value2, UUID value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserHeaderJQR
	 */
	public UserHeaderJQR() {
		super(TblUserHeader.USER_HEADER);
	}

	/**
	 * Create a detached, initialised UserHeaderJQR
	 */
	public UserHeaderJQR(UUID userId, String userName, UUID avatarImg) {
		super(TblUserHeader.USER_HEADER);

		setValue(0, userId);
		setValue(1, userName);
		setValue(2, avatarImg);
	}
}
