/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblUserNoteFood;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNoteFoodJQR extends UpdatableRecordImpl<UserNoteFoodJQR> implements Record2<Long, Long> {

	private static final long serialVersionUID = 1981958865;

	/**
	 * Setter for <code>mic_core.user_note_food.note_id</code>.
	 */
	public void setNoteId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_food.note_id</code>.
	 */
	public Long getNoteId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_note_food.food_id</code>.
	 */
	public void setFoodId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_note_food.food_id</code>.
	 */
	public Long getFoodId() {
		return (Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Long> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblUserNoteFood.USER_NOTE_FOOD.NOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblUserNoteFood.USER_NOTE_FOOD.FOOD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getNoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getFoodId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteFoodJQR value1(Long value) {
		setNoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteFoodJQR value2(Long value) {
		setFoodId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserNoteFoodJQR values(Long value1, Long value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserNoteFoodJQR
	 */
	public UserNoteFoodJQR() {
		super(TblUserNoteFood.USER_NOTE_FOOD);
	}

	/**
	 * Create a detached, initialised UserNoteFoodJQR
	 */
	public UserNoteFoodJQR(Long noteId, Long foodId) {
		super(TblUserNoteFood.USER_NOTE_FOOD);

		setValue(0, noteId);
		setValue(1, foodId);
	}
}
