/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblUserCellar;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCellarJQR extends UpdatableRecordImpl<UserCellarJQR> implements Record7<UUID, Long, Short, Integer, String, UUID, Integer> {

	private static final long serialVersionUID = 1222710373;

	/**
	 * Setter for <code>mic_core.user_cellar.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.quantity</code>.
	 */
	public void setQuantity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.quantity</code>.
	 */
	public Integer getQuantity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.note</code>.
	 */
	public void setNote(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.note</code>.
	 */
	public String getNote() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.wine_img</code>.
	 */
	public void setWineImg(UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.wine_img</code>.
	 */
	public UUID getWineImg() {
		return (UUID) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.user_cellar.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.user_cellar.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<UUID, Long, Short> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, Long, Short, Integer, String, UUID, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, Long, Short, Integer, String, UUID, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblUserCellar.USER_CELLAR.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblUserCellar.USER_CELLAR.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblUserCellar.USER_CELLAR.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return TblUserCellar.USER_CELLAR.QUANTITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblUserCellar.USER_CELLAR.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field6() {
		return TblUserCellar.USER_CELLAR.WINE_IMG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return TblUserCellar.USER_CELLAR.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getQuantity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value6() {
		return getWineImg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value2(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value3(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value4(Integer value) {
		setQuantity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value5(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value6(UUID value) {
		setWineImg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR value7(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserCellarJQR values(UUID value1, Long value2, Short value3, Integer value4, String value5, UUID value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserCellarJQR
	 */
	public UserCellarJQR() {
		super(TblUserCellar.USER_CELLAR);
	}

	/**
	 * Create a detached, initialised UserCellarJQR
	 */
	public UserCellarJQR(UUID userId, Long wineId, Short vintageTag, Integer quantity, String note, UUID wineImg, Integer lastUpdMictime) {
		super(TblUserCellar.USER_CELLAR);

		setValue(0, userId);
		setValue(1, wineId);
		setValue(2, vintageTag);
		setValue(3, quantity);
		setValue(4, note);
		setValue(5, wineImg);
		setValue(6, lastUpdMictime);
	}
}
