/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblVintageAttr;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VintageAttrJQR extends UpdatableRecordImpl<VintageAttrJQR> implements Record5<Long, Short, Long, Short, Integer> {

	private static final long serialVersionUID = -343429315;

	/**
	 * Setter for <code>mic_core.vintage_attr.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.vintage_attr.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.vintage_attr.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.vintage_attr.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.vintage_attr.attr_id</code>.
	 */
	public void setAttrId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.vintage_attr.attr_id</code>.
	 */
	public Long getAttrId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.vintage_attr.attr_assoc_val</code>.
	 */
	public void setAttrAssocVal(Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.vintage_attr.attr_assoc_val</code>.
	 */
	public Short getAttrAssocVal() {
		return (Short) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.vintage_attr.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.vintage_attr.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Long, Short, Long> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Short, Long, Short, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Short, Long, Short, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblVintageAttr.VINTAGE_ATTR.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblVintageAttr.VINTAGE_ATTR.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return TblVintageAttr.VINTAGE_ATTR.ATTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field4() {
		return TblVintageAttr.VINTAGE_ATTR.ATTR_ASSOC_VAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TblVintageAttr.VINTAGE_ATTR.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getAttrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value4() {
		return getAttrAssocVal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR value1(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR value2(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR value3(Long value) {
		setAttrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR value4(Short value) {
		setAttrAssocVal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR value5(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageAttrJQR values(Long value1, Short value2, Long value3, Short value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VintageAttrJQR
	 */
	public VintageAttrJQR() {
		super(TblVintageAttr.VINTAGE_ATTR);
	}

	/**
	 * Create a detached, initialised VintageAttrJQR
	 */
	public VintageAttrJQR(Long wineId, Short vintageTag, Long attrId, Short attrAssocVal, Integer lastUpdMictime) {
		super(TblVintageAttr.VINTAGE_ATTR);

		setValue(0, wineId);
		setValue(1, vintageTag);
		setValue(2, attrId);
		setValue(3, attrAssocVal);
		setValue(4, lastUpdMictime);
	}
}
