/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblVintage;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VintageJQR extends UpdatableRecordImpl<VintageJQR> implements Record7<Long, Short, String, String, UUID, Boolean, String> {

	private static final long serialVersionUID = -1109043987;

	/**
	 * Setter for <code>mic_core.vintage.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.vintage.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.vintage.vintage_name</code>.
	 */
	public void setVintageName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.vintage_name</code>.
	 */
	public String getVintageName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.vintage.note</code>.
	 */
	public void setNote(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.note</code>.
	 */
	public String getNote() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.vintage.vintage_img</code>.
	 */
	public void setVintageImg(UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.vintage_img</code>.
	 */
	public UUID getVintageImg() {
		return (UUID) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.vintage.is_valid</code>.
	 */
	public void setIsValid(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.is_valid</code>.
	 */
	public Boolean getIsValid() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.vintage.seo_url</code>.
	 */
	public void setSeoUrl(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.vintage.seo_url</code>.
	 */
	public String getSeoUrl() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Short> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Short, String, String, UUID, Boolean, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Long, Short, String, String, UUID, Boolean, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblVintage.VINTAGE.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblVintage.VINTAGE.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblVintage.VINTAGE.VINTAGE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblVintage.VINTAGE.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field5() {
		return TblVintage.VINTAGE.VINTAGE_IMG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TblVintage.VINTAGE.IS_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblVintage.VINTAGE.SEO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getVintageName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value5() {
		return getVintageImg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSeoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value1(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value2(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value3(String value) {
		setVintageName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value4(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value5(UUID value) {
		setVintageImg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value6(Boolean value) {
		setIsValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR value7(String value) {
		setSeoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VintageJQR values(Long value1, Short value2, String value3, String value4, UUID value5, Boolean value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VintageJQR
	 */
	public VintageJQR() {
		super(TblVintage.VINTAGE);
	}

	/**
	 * Create a detached, initialised VintageJQR
	 */
	public VintageJQR(Long wineId, Short vintageTag, String vintageName, String note, UUID vintageImg, Boolean isValid, String seoUrl) {
		super(TblVintage.VINTAGE);

		setValue(0, wineId);
		setValue(1, vintageTag);
		setValue(2, vintageName);
		setValue(3, note);
		setValue(4, vintageImg);
		setValue(5, isValid);
		setValue(6, seoUrl);
	}
}
