/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblWineryCountry;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineryCountryJQR extends UpdatableRecordImpl<WineryCountryJQR> implements Record8<Integer, String, Short, String, String, String, String, String> {

	private static final long serialVersionUID = 1778463306;

	/**
	 * Setter for <code>mic_core.winery_country.country_id</code>.
	 */
	public void setCountryId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.country_id</code>.
	 */
	public Integer getCountryId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.winery_country.country_code</code>.
	 */
	public void setCountryCode(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.country_code</code>.
	 */
	public String getCountryCode() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.winery_country.rank</code>.
	 */
	public void setRank(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.rank</code>.
	 */
	public Short getRank() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.winery_country.country_name_eng</code>.
	 */
	public void setCountryNameEng(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.country_name_eng</code>.
	 */
	public String getCountryNameEng() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.winery_country.country_name_chs</code>.
	 */
	public void setCountryNameChs(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.country_name_chs</code>.
	 */
	public String getCountryNameChs() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.winery_country.country_name_cht</code>.
	 */
	public void setCountryNameCht(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.country_name_cht</code>.
	 */
	public String getCountryNameCht() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.winery_country.note</code>.
	 */
	public void setNote(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.note</code>.
	 */
	public String getNote() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.winery_country.seo_url</code>.
	 */
	public void setSeoUrl(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.winery_country.seo_url</code>.
	 */
	public String getSeoUrl() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Short, String, String, String, String, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Short, String, String, String, String, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TblWineryCountry.WINERY_COUNTRY.COUNTRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TblWineryCountry.WINERY_COUNTRY.COUNTRY_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblWineryCountry.WINERY_COUNTRY.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblWineryCountry.WINERY_COUNTRY.COUNTRY_NAME_ENG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblWineryCountry.WINERY_COUNTRY.COUNTRY_NAME_CHS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblWineryCountry.WINERY_COUNTRY.COUNTRY_NAME_CHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblWineryCountry.WINERY_COUNTRY.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TblWineryCountry.WINERY_COUNTRY.SEO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCountryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCountryCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCountryNameEng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCountryNameChs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCountryNameCht();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSeoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value1(Integer value) {
		setCountryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value2(String value) {
		setCountryCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value3(Short value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value4(String value) {
		setCountryNameEng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value5(String value) {
		setCountryNameChs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value6(String value) {
		setCountryNameCht(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value7(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR value8(String value) {
		setSeoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryCountryJQR values(Integer value1, String value2, Short value3, String value4, String value5, String value6, String value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WineryCountryJQR
	 */
	public WineryCountryJQR() {
		super(TblWineryCountry.WINERY_COUNTRY);
	}

	/**
	 * Create a detached, initialised WineryCountryJQR
	 */
	public WineryCountryJQR(Integer countryId, String countryCode, Short rank, String countryNameEng, String countryNameChs, String countryNameCht, String note, String seoUrl) {
		super(TblWineryCountry.WINERY_COUNTRY);

		setValue(0, countryId);
		setValue(1, countryCode);
		setValue(2, rank);
		setValue(3, countryNameEng);
		setValue(4, countryNameChs);
		setValue(5, countryNameCht);
		setValue(6, note);
		setValue(7, seoUrl);
	}
}
