/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import myicellar.jooq.tables.TblWineName;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineNameJQR extends UpdatableRecordImpl<WineNameJQR> implements Record8<Long, Long, String, String, String, String, Boolean, Integer> {

	private static final long serialVersionUID = -763932858;

	/**
	 * Setter for <code>mic_core.wine_name.wine_name_id</code>.
	 */
	public void setWineNameId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_name_id</code>.
	 */
	public Long getWineNameId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.wine_name.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.wine_name.wine_name_usr</code>.
	 */
	public void setWineNameUsr(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_name_usr</code>.
	 */
	public String getWineNameUsr() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.wine_name.wine_name_eng</code>.
	 */
	public void setWineNameEng(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_name_eng</code>.
	 */
	public String getWineNameEng() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.wine_name.wine_name_chs</code>.
	 */
	public void setWineNameChs(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_name_chs</code>.
	 */
	public String getWineNameChs() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.wine_name.wine_name_cht</code>.
	 */
	public void setWineNameCht(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.wine_name_cht</code>.
	 */
	public String getWineNameCht() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.wine_name.is_valid</code>.
	 */
	public void setIsValid(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.is_valid</code>.
	 */
	public Boolean getIsValid() {
		return (Boolean) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.wine_name.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.wine_name.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Long, String, String, String, String, Boolean, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Long, String, String, String, String, Boolean, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblWineName.WINE_NAME.WINE_NAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblWineName.WINE_NAME.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TblWineName.WINE_NAME.WINE_NAME_USR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblWineName.WINE_NAME.WINE_NAME_ENG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblWineName.WINE_NAME.WINE_NAME_CHS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblWineName.WINE_NAME.WINE_NAME_CHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return TblWineName.WINE_NAME.IS_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return TblWineName.WINE_NAME.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getWineNameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getWineNameUsr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getWineNameEng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getWineNameChs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getWineNameCht();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getIsValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value1(Long value) {
		setWineNameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value2(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value3(String value) {
		setWineNameUsr(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value4(String value) {
		setWineNameEng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value5(String value) {
		setWineNameChs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value6(String value) {
		setWineNameCht(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value7(Boolean value) {
		setIsValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR value8(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineNameJQR values(Long value1, Long value2, String value3, String value4, String value5, String value6, Boolean value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WineNameJQR
	 */
	public WineNameJQR() {
		super(TblWineName.WINE_NAME);
	}

	/**
	 * Create a detached, initialised WineNameJQR
	 */
	public WineNameJQR(Long wineNameId, Long wineId, String wineNameUsr, String wineNameEng, String wineNameChs, String wineNameCht, Boolean isValid, Integer lastUpdMictime) {
		super(TblWineName.WINE_NAME);

		setValue(0, wineNameId);
		setValue(1, wineId);
		setValue(2, wineNameUsr);
		setValue(3, wineNameEng);
		setValue(4, wineNameChs);
		setValue(5, wineNameCht);
		setValue(6, isValid);
		setValue(7, lastUpdMictime);
	}
}
