/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.util.UUID;

import myicellar.jooq.tables.TblWineryRegion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WineryRegionJQR extends UpdatableRecordImpl<WineryRegionJQR> implements Record11<Integer, Integer, Integer, String, String, String, String, UUID, Boolean, String, Integer> {

	private static final long serialVersionUID = 1707246479;

	/**
	 * Setter for <code>mic_core.winery_region.region_id</code>.
	 */
	public void setRegionId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_id</code>.
	 */
	public Integer getRegionId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.winery_region.region_alt_id</code>.
	 */
	public void setRegionAltId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_alt_id</code>.
	 */
	public Integer getRegionAltId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.winery_region.country_id</code>.
	 */
	public void setCountryId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.country_id</code>.
	 */
	public Integer getCountryId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.winery_region.region_name_eng</code>.
	 */
	public void setRegionNameEng(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_name_eng</code>.
	 */
	public String getRegionNameEng() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.winery_region.region_name_chs</code>.
	 */
	public void setRegionNameChs(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_name_chs</code>.
	 */
	public String getRegionNameChs() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.winery_region.region_name_cht</code>.
	 */
	public void setRegionNameCht(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_name_cht</code>.
	 */
	public String getRegionNameCht() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>mic_core.winery_region.note</code>.
	 */
	public void setNote(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.note</code>.
	 */
	public String getNote() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>mic_core.winery_region.region_img</code>.
	 */
	public void setRegionImg(UUID value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.region_img</code>.
	 */
	public UUID getRegionImg() {
		return (UUID) getValue(7);
	}

	/**
	 * Setter for <code>mic_core.winery_region.is_valid</code>.
	 */
	public void setIsValid(Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.is_valid</code>.
	 */
	public Boolean getIsValid() {
		return (Boolean) getValue(8);
	}

	/**
	 * Setter for <code>mic_core.winery_region.seo_url</code>.
	 */
	public void setSeoUrl(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.seo_url</code>.
	 */
	public String getSeoUrl() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>mic_core.winery_region.last_upd_mictime</code>.
	 */
	public void setLastUpdMictime(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mic_core.winery_region.last_upd_mictime</code>.
	 */
	public Integer getLastUpdMictime() {
		return (Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, String, String, String, String, UUID, Boolean, String, Integer> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, String, String, String, String, UUID, Boolean, String, Integer> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TblWineryRegion.WINERY_REGION.REGION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TblWineryRegion.WINERY_REGION.REGION_ALT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TblWineryRegion.WINERY_REGION.COUNTRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TblWineryRegion.WINERY_REGION.REGION_NAME_ENG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TblWineryRegion.WINERY_REGION.REGION_NAME_CHS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TblWineryRegion.WINERY_REGION.REGION_NAME_CHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TblWineryRegion.WINERY_REGION.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field8() {
		return TblWineryRegion.WINERY_REGION.REGION_IMG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field9() {
		return TblWineryRegion.WINERY_REGION.IS_VALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TblWineryRegion.WINERY_REGION.SEO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return TblWineryRegion.WINERY_REGION.LAST_UPD_MICTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRegionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRegionAltId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCountryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getRegionNameEng();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getRegionNameChs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getRegionNameCht();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value8() {
		return getRegionImg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value9() {
		return getIsValid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSeoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getLastUpdMictime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value1(Integer value) {
		setRegionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value2(Integer value) {
		setRegionAltId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value3(Integer value) {
		setCountryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value4(String value) {
		setRegionNameEng(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value5(String value) {
		setRegionNameChs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value6(String value) {
		setRegionNameCht(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value7(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value8(UUID value) {
		setRegionImg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value9(Boolean value) {
		setIsValid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value10(String value) {
		setSeoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR value11(Integer value) {
		setLastUpdMictime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WineryRegionJQR values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, UUID value8, Boolean value9, String value10, Integer value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WineryRegionJQR
	 */
	public WineryRegionJQR() {
		super(TblWineryRegion.WINERY_REGION);
	}

	/**
	 * Create a detached, initialised WineryRegionJQR
	 */
	public WineryRegionJQR(Integer regionId, Integer regionAltId, Integer countryId, String regionNameEng, String regionNameChs, String regionNameCht, String note, UUID regionImg, Boolean isValid, String seoUrl, Integer lastUpdMictime) {
		super(TblWineryRegion.WINERY_REGION);

		setValue(0, regionId);
		setValue(1, regionAltId);
		setValue(2, countryId);
		setValue(3, regionNameEng);
		setValue(4, regionNameChs);
		setValue(5, regionNameCht);
		setValue(6, note);
		setValue(7, regionImg);
		setValue(8, isValid);
		setValue(9, seoUrl);
		setValue(10, lastUpdMictime);
	}
}
