/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblZyAttrAbvintage;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZyAttrAbvintageJQR extends TableRecordImpl<ZyAttrAbvintageJQR> implements Record4<Long, Short, Timestamp, UUID> {

	private static final long serialVersionUID = 577832218;

	/**
	 * Setter for <code>mic_core.zy_attr_abvintage.attr_id</code>.
	 */
	public void setAttrId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.zy_attr_abvintage.attr_id</code>.
	 */
	public Long getAttrId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.zy_attr_abvintage.action_name_id</code>.
	 */
	public void setActionNameId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.zy_attr_abvintage.action_name_id</code>.
	 */
	public Short getActionNameId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.zy_attr_abvintage.action_time</code>.
	 */
	public void setActionTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.zy_attr_abvintage.action_time</code>.
	 */
	public Timestamp getActionTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.zy_attr_abvintage.action_by</code>.
	 */
	public void setActionBy(UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.zy_attr_abvintage.action_by</code>.
	 */
	public UUID getActionBy() {
		return (UUID) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Short, Timestamp, UUID> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Short, Timestamp, UUID> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE.ATTR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE.ACTION_NAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE.ACTION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field4() {
		return TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE.ACTION_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAttrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getActionNameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getActionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value4() {
		return getActionBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAttrAbvintageJQR value1(Long value) {
		setAttrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAttrAbvintageJQR value2(Short value) {
		setActionNameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAttrAbvintageJQR value3(Timestamp value) {
		setActionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAttrAbvintageJQR value4(UUID value) {
		setActionBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAttrAbvintageJQR values(Long value1, Short value2, Timestamp value3, UUID value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ZyAttrAbvintageJQR
	 */
	public ZyAttrAbvintageJQR() {
		super(TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE);
	}

	/**
	 * Create a detached, initialised ZyAttrAbvintageJQR
	 */
	public ZyAttrAbvintageJQR(Long attrId, Short actionNameId, Timestamp actionTime, UUID actionBy) {
		super(TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE);

		setValue(0, attrId);
		setValue(1, actionNameId);
		setValue(2, actionTime);
		setValue(3, actionBy);
	}
}
