/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblZyAtagAbnote;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZyAtagAbnoteJQR extends TableRecordImpl<ZyAtagAbnoteJQR> implements Record4<Long, Short, Timestamp, UUID> {

	private static final long serialVersionUID = 1712886537;

	/**
	 * Setter for <code>mic_core.zy_atag_abnote.atag_id</code>.
	 */
	public void setAtagId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.zy_atag_abnote.atag_id</code>.
	 */
	public Long getAtagId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.zy_atag_abnote.action_type_id</code>.
	 */
	public void setActionTypeId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.zy_atag_abnote.action_type_id</code>.
	 */
	public Short getActionTypeId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.zy_atag_abnote.action_time</code>.
	 */
	public void setActionTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.zy_atag_abnote.action_time</code>.
	 */
	public Timestamp getActionTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.zy_atag_abnote.action_by</code>.
	 */
	public void setActionBy(UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.zy_atag_abnote.action_by</code>.
	 */
	public UUID getActionBy() {
		return (UUID) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Short, Timestamp, UUID> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Short, Timestamp, UUID> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblZyAtagAbnote.ZY_ATAG_ABNOTE.ATAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblZyAtagAbnote.ZY_ATAG_ABNOTE.ACTION_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return TblZyAtagAbnote.ZY_ATAG_ABNOTE.ACTION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field4() {
		return TblZyAtagAbnote.ZY_ATAG_ABNOTE.ACTION_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAtagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getActionTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getActionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value4() {
		return getActionBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAtagAbnoteJQR value1(Long value) {
		setAtagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAtagAbnoteJQR value2(Short value) {
		setActionTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAtagAbnoteJQR value3(Timestamp value) {
		setActionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAtagAbnoteJQR value4(UUID value) {
		setActionBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyAtagAbnoteJQR values(Long value1, Short value2, Timestamp value3, UUID value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ZyAtagAbnoteJQR
	 */
	public ZyAtagAbnoteJQR() {
		super(TblZyAtagAbnote.ZY_ATAG_ABNOTE);
	}

	/**
	 * Create a detached, initialised ZyAtagAbnoteJQR
	 */
	public ZyAtagAbnoteJQR(Long atagId, Short actionTypeId, Timestamp actionTime, UUID actionBy) {
		super(TblZyAtagAbnote.ZY_ATAG_ABNOTE);

		setValue(0, atagId);
		setValue(1, actionTypeId);
		setValue(2, actionTime);
		setValue(3, actionBy);
	}
}
