/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblZyUserCellar;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZyUserCellarJQR extends TableRecordImpl<ZyUserCellarJQR> implements Record6<UUID, Long, Short, Short, Timestamp, UUID> {

	private static final long serialVersionUID = 1593109787;

	/**
	 * Setter for <code>mic_core.zy_user_cellar.user_id</code>.
	 */
	public void setUserId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.user_id</code>.
	 */
	public UUID getUserId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.zy_user_cellar.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.zy_user_cellar.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.zy_user_cellar.action_type</code>.
	 */
	public void setActionType(Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.action_type</code>.
	 */
	public Short getActionType() {
		return (Short) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.zy_user_cellar.action_time</code>.
	 */
	public void setActionTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.action_time</code>.
	 */
	public Timestamp getActionTime() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>mic_core.zy_user_cellar.action_by</code>.
	 */
	public void setActionBy(UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mic_core.zy_user_cellar.action_by</code>.
	 */
	public UUID getActionBy() {
		return (UUID) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<UUID, Long, Short, Short, Timestamp, UUID> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<UUID, Long, Short, Short, Timestamp, UUID> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return TblZyUserCellar.ZY_USER_CELLAR.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return TblZyUserCellar.ZY_USER_CELLAR.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblZyUserCellar.ZY_USER_CELLAR.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field4() {
		return TblZyUserCellar.ZY_USER_CELLAR.ACTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return TblZyUserCellar.ZY_USER_CELLAR.ACTION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field6() {
		return TblZyUserCellar.ZY_USER_CELLAR.ACTION_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value4() {
		return getActionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getActionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value6() {
		return getActionBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value1(UUID value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value2(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value3(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value4(Short value) {
		setActionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value5(Timestamp value) {
		setActionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR value6(UUID value) {
		setActionBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyUserCellarJQR values(UUID value1, Long value2, Short value3, Short value4, Timestamp value5, UUID value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ZyUserCellarJQR
	 */
	public ZyUserCellarJQR() {
		super(TblZyUserCellar.ZY_USER_CELLAR);
	}

	/**
	 * Create a detached, initialised ZyUserCellarJQR
	 */
	public ZyUserCellarJQR(UUID userId, Long wineId, Short vintageTag, Short actionType, Timestamp actionTime, UUID actionBy) {
		super(TblZyUserCellar.ZY_USER_CELLAR);

		setValue(0, userId);
		setValue(1, wineId);
		setValue(2, vintageTag);
		setValue(3, actionType);
		setValue(4, actionTime);
		setValue(5, actionBy);
	}
}
