/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblZyVintage;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZyVintageJQR extends TableRecordImpl<ZyVintageJQR> implements Record5<Long, Short, Short, Timestamp, UUID> {

	private static final long serialVersionUID = -930770559;

	/**
	 * Setter for <code>mic_core.zy_vintage.wine_id</code>.
	 */
	public void setWineId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.zy_vintage.wine_id</code>.
	 */
	public Long getWineId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.zy_vintage.vintage_tag</code>.
	 */
	public void setVintageTag(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.zy_vintage.vintage_tag</code>.
	 */
	public Short getVintageTag() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.zy_vintage.action_type</code>.
	 */
	public void setActionType(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.zy_vintage.action_type</code>.
	 */
	public Short getActionType() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.zy_vintage.action_time</code>.
	 */
	public void setActionTime(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.zy_vintage.action_time</code>.
	 */
	public Timestamp getActionTime() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>mic_core.zy_vintage.action_by</code>.
	 */
	public void setActionBy(UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mic_core.zy_vintage.action_by</code>.
	 */
	public UUID getActionBy() {
		return (UUID) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Short, Short, Timestamp, UUID> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Short, Short, Timestamp, UUID> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TblZyVintage.ZY_VINTAGE.WINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblZyVintage.ZY_VINTAGE.VINTAGE_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return TblZyVintage.ZY_VINTAGE.ACTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return TblZyVintage.ZY_VINTAGE.ACTION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field5() {
		return TblZyVintage.ZY_VINTAGE.ACTION_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getWineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getVintageTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getActionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getActionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value5() {
		return getActionBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR value1(Long value) {
		setWineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR value2(Short value) {
		setVintageTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR value3(Short value) {
		setActionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR value4(Timestamp value) {
		setActionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR value5(UUID value) {
		setActionBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyVintageJQR values(Long value1, Short value2, Short value3, Timestamp value4, UUID value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ZyVintageJQR
	 */
	public ZyVintageJQR() {
		super(TblZyVintage.ZY_VINTAGE);
	}

	/**
	 * Create a detached, initialised ZyVintageJQR
	 */
	public ZyVintageJQR(Long wineId, Short vintageTag, Short actionType, Timestamp actionTime, UUID actionBy) {
		super(TblZyVintage.ZY_VINTAGE);

		setValue(0, wineId);
		setValue(1, vintageTag);
		setValue(2, actionType);
		setValue(3, actionTime);
		setValue(4, actionBy);
	}
}
