/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.records;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.tables.TblZyWineryRegion;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZyWineryRegionJQR extends TableRecordImpl<ZyWineryRegionJQR> implements Record4<Integer, Short, Timestamp, UUID> {

	private static final long serialVersionUID = 1048623418;

	/**
	 * Setter for <code>mic_core.zy_winery_region.region_id</code>.
	 */
	public void setRegionId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mic_core.zy_winery_region.region_id</code>.
	 */
	public Integer getRegionId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mic_core.zy_winery_region.action_type</code>.
	 */
	public void setActionType(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mic_core.zy_winery_region.action_type</code>.
	 */
	public Short getActionType() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>mic_core.zy_winery_region.action_time</code>.
	 */
	public void setActionTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mic_core.zy_winery_region.action_time</code>.
	 */
	public Timestamp getActionTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>mic_core.zy_winery_region.action_by</code>.
	 */
	public void setActionBy(UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mic_core.zy_winery_region.action_by</code>.
	 */
	public UUID getActionBy() {
		return (UUID) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Short, Timestamp, UUID> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Short, Timestamp, UUID> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TblZyWineryRegion.ZY_WINERY_REGION.REGION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return TblZyWineryRegion.ZY_WINERY_REGION.ACTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return TblZyWineryRegion.ZY_WINERY_REGION.ACTION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field4() {
		return TblZyWineryRegion.ZY_WINERY_REGION.ACTION_BY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRegionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getActionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getActionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value4() {
		return getActionBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyWineryRegionJQR value1(Integer value) {
		setRegionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyWineryRegionJQR value2(Short value) {
		setActionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyWineryRegionJQR value3(Timestamp value) {
		setActionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyWineryRegionJQR value4(UUID value) {
		setActionBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ZyWineryRegionJQR values(Integer value1, Short value2, Timestamp value3, UUID value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ZyWineryRegionJQR
	 */
	public ZyWineryRegionJQR() {
		super(TblZyWineryRegion.ZY_WINERY_REGION);
	}

	/**
	 * Create a detached, initialised ZyWineryRegionJQR
	 */
	public ZyWineryRegionJQR(Integer regionId, Short actionType, Timestamp actionTime, UUID actionBy) {
		super(TblZyWineryRegion.ZY_WINERY_REGION);

		setValue(0, regionId);
		setValue(1, actionType);
		setValue(2, actionTime);
		setValue(3, actionBy);
	}
}
