/**
 * This class is generated by jOOQ
 */
package myicellar.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import myicellar.jooq.tables.TblAtagAbnote;
import myicellar.jooq.tables.TblAttrAbnote;
import myicellar.jooq.tables.TblAttrAbvintage;
import myicellar.jooq.tables.TblAttrAbvintageFolw;
import myicellar.jooq.tables.TblAttrName;
import myicellar.jooq.tables.TblCity;
import myicellar.jooq.tables.TblFood;
import myicellar.jooq.tables.TblPlace;
import myicellar.jooq.tables.TblUauthLastlogin;
import myicellar.jooq.tables.TblUauthPwdreset;
import myicellar.jooq.tables.TblUauthSclntw;
import myicellar.jooq.tables.TblUauthSession;
import myicellar.jooq.tables.TblUauthSimple;
import myicellar.jooq.tables.TblUserCellar;
import myicellar.jooq.tables.TblUserCountry;
import myicellar.jooq.tables.TblUserDlvrProf;
import myicellar.jooq.tables.TblUserFavWine;
import myicellar.jooq.tables.TblUserHeader;
import myicellar.jooq.tables.TblUserNote;
import myicellar.jooq.tables.TblUserNoteAtag;
import myicellar.jooq.tables.TblUserNoteAttr;
import myicellar.jooq.tables.TblUserNoteFeatured;
import myicellar.jooq.tables.TblUserNoteFood;
import myicellar.jooq.tables.TblUserNotification;
import myicellar.jooq.tables.TblUserOccas;
import myicellar.jooq.tables.TblUserOccasWith;
import myicellar.jooq.tables.TblUserProfile;
import myicellar.jooq.tables.TblUserUptoFolw;
import myicellar.jooq.tables.TblVintage;
import myicellar.jooq.tables.TblVintageAttr;
import myicellar.jooq.tables.TblWine;
import myicellar.jooq.tables.TblWineName;
import myicellar.jooq.tables.TblWineType;
import myicellar.jooq.tables.TblWineTypeFolw;
import myicellar.jooq.tables.TblWinery;
import myicellar.jooq.tables.TblWineryCountry;
import myicellar.jooq.tables.TblWineryCountryFolw;
import myicellar.jooq.tables.TblWineryFolw;
import myicellar.jooq.tables.TblWineryRegion;
import myicellar.jooq.tables.TblWineryRegionFolw;
import myicellar.jooq.tables.TblZyAtagAbnote;
import myicellar.jooq.tables.TblZyAttrAbnote;
import myicellar.jooq.tables.TblZyAttrAbvintage;
import myicellar.jooq.tables.TblZyFood;
import myicellar.jooq.tables.TblZyPlace;
import myicellar.jooq.tables.TblZyUserCellar;
import myicellar.jooq.tables.TblZyUserNote;
import myicellar.jooq.tables.TblZyUserOccas;
import myicellar.jooq.tables.TblZyVintage;
import myicellar.jooq.tables.TblZyWine;
import myicellar.jooq.tables.TblZyWineName;
import myicellar.jooq.tables.TblZyWinery;
import myicellar.jooq.tables.TblZyWineryRegion;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MicCore extends SchemaImpl {

	private static final long serialVersionUID = -853927334;

	/**
	 * The reference instance of <code>mic_core</code>
	 */
	public static final MicCore MIC_CORE = new MicCore();

	/**
	 * No further instances allowed
	 */
	private MicCore() {
		super("mic_core");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			TblAtagAbnote.ATAG_ABNOTE,
			TblAttrAbnote.ATTR_ABNOTE,
			TblAttrAbvintage.ATTR_ABVINTAGE,
			TblAttrAbvintageFolw.ATTR_ABVINTAGE_FOLW,
			TblAttrName.ATTR_NAME,
			TblCity.CITY,
			TblFood.FOOD,
			TblPlace.PLACE,
			TblUauthLastlogin.UAUTH_LASTLOGIN,
			TblUauthPwdreset.UAUTH_PWDRESET,
			TblUauthSclntw.UAUTH_SCLNTW,
			TblUauthSession.UAUTH_SESSION,
			TblUauthSimple.UAUTH_SIMPLE,
			TblUserCellar.USER_CELLAR,
			TblUserCountry.USER_COUNTRY,
			TblUserDlvrProf.USER_DLVR_PROF,
			TblUserFavWine.USER_FAV_WINE,
			TblUserHeader.USER_HEADER,
			TblUserNote.USER_NOTE,
			TblUserNoteAtag.USER_NOTE_ATAG,
			TblUserNoteAttr.USER_NOTE_ATTR,
			TblUserNoteFeatured.USER_NOTE_FEATURED,
			TblUserNoteFood.USER_NOTE_FOOD,
			TblUserNotification.USER_NOTIFICATION,
			TblUserOccas.USER_OCCAS,
			TblUserOccasWith.USER_OCCAS_WITH,
			TblUserProfile.USER_PROFILE,
			TblUserUptoFolw.USER_UPTO_FOLW,
			TblVintage.VINTAGE,
			TblVintageAttr.VINTAGE_ATTR,
			TblWine.WINE,
			TblWineName.WINE_NAME,
			TblWinery.WINERY,
			TblWineryCountry.WINERY_COUNTRY,
			TblWineryCountryFolw.WINERY_COUNTRY_FOLW,
			TblWineryFolw.WINERY_FOLW,
			TblWineryRegion.WINERY_REGION,
			TblWineryRegionFolw.WINERY_REGION_FOLW,
			TblWineType.WINE_TYPE,
			TblWineTypeFolw.WINE_TYPE_FOLW,
			TblZyAtagAbnote.ZY_ATAG_ABNOTE,
			TblZyAttrAbnote.ZY_ATTR_ABNOTE,
			TblZyAttrAbvintage.ZY_ATTR_ABVINTAGE,
			TblZyFood.ZY_FOOD,
			TblZyPlace.ZY_PLACE,
			TblZyUserCellar.ZY_USER_CELLAR,
			TblZyUserNote.ZY_USER_NOTE,
			TblZyUserOccas.ZY_USER_OCCAS,
			TblZyVintage.ZY_VINTAGE,
			TblZyWine.ZY_WINE,
			TblZyWineName.ZY_WINE_NAME,
			TblZyWinery.ZY_WINERY,
			TblZyWineryRegion.ZY_WINERY_REGION);
	}
}
