/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.AttrAbvintageFolwJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAttrAbvintageFolw extends TableImpl<AttrAbvintageFolwJQR> {

	private static final long serialVersionUID = -2099367341;

	/**
	 * The reference instance of <code>mic_core.attr_abvintage_folw</code>
	 */
	public static final TblAttrAbvintageFolw ATTR_ABVINTAGE_FOLW = new TblAttrAbvintageFolw();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AttrAbvintageFolwJQR> getRecordType() {
		return AttrAbvintageFolwJQR.class;
	}

	/**
	 * The column <code>mic_core.attr_abvintage_folw.user_id</code>.
	 */
	public final TableField<AttrAbvintageFolwJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.attr_abvintage_folw.attr_id</code>.
	 */
	public final TableField<AttrAbvintageFolwJQR, Long> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>mic_core.attr_abvintage_folw.last_upd_mictime</code>.
	 */
	public final TableField<AttrAbvintageFolwJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.attr_abvintage_folw</code> table reference
	 */
	public TblAttrAbvintageFolw() {
		this("attr_abvintage_folw", null);
	}

	/**
	 * Create an aliased <code>mic_core.attr_abvintage_folw</code> table reference
	 */
	public TblAttrAbvintageFolw(String alias) {
		this(alias, ATTR_ABVINTAGE_FOLW);
	}

	private TblAttrAbvintageFolw(String alias, Table<AttrAbvintageFolwJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblAttrAbvintageFolw(String alias, Table<AttrAbvintageFolwJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblAttrAbvintageFolw as(String alias) {
		return new TblAttrAbvintageFolw(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblAttrAbvintageFolw rename(String name) {
		return new TblAttrAbvintageFolw(name, null);
	}
}
