/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.AttrAbvintageJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAttrAbvintage extends TableImpl<AttrAbvintageJQR> {

	private static final long serialVersionUID = -1561930599;

	/**
	 * The reference instance of <code>mic_core.attr_abvintage</code>
	 */
	public static final TblAttrAbvintage ATTR_ABVINTAGE = new TblAttrAbvintage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AttrAbvintageJQR> getRecordType() {
		return AttrAbvintageJQR.class;
	}

	/**
	 * The column <code>mic_core.attr_abvintage.attr_id</code>.
	 */
	public final TableField<AttrAbvintageJQR, Long> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.attr_name_id</code>.
	 */
	public final TableField<AttrAbvintageJQR, Short> ATTR_NAME_ID = createField("attr_name_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.attr_val_eng</code>.
	 */
	public final TableField<AttrAbvintageJQR, String> ATTR_VAL_ENG = createField("attr_val_eng", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.attr_val_chs</code>.
	 */
	public final TableField<AttrAbvintageJQR, String> ATTR_VAL_CHS = createField("attr_val_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.attr_val_cht</code>.
	 */
	public final TableField<AttrAbvintageJQR, String> ATTR_VAL_CHT = createField("attr_val_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.is_valid</code>.
	 */
	public final TableField<AttrAbvintageJQR, Boolean> IS_VALID = createField("is_valid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>mic_core.attr_abvintage.last_upd_mictime</code>.
	 */
	public final TableField<AttrAbvintageJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.attr_abvintage</code> table reference
	 */
	public TblAttrAbvintage() {
		this("attr_abvintage", null);
	}

	/**
	 * Create an aliased <code>mic_core.attr_abvintage</code> table reference
	 */
	public TblAttrAbvintage(String alias) {
		this(alias, ATTR_ABVINTAGE);
	}

	private TblAttrAbvintage(String alias, Table<AttrAbvintageJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblAttrAbvintage(String alias, Table<AttrAbvintageJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AttrAbvintageJQR, Long> getIdentity() {
		return Keys.IDENTITY_ATTR_ABVINTAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AttrAbvintageJQR> getPrimaryKey() {
		return Keys.ATTR_ABVINTAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AttrAbvintageJQR>> getKeys() {
		return Arrays.<UniqueKey<AttrAbvintageJQR>>asList(Keys.ATTR_ABVINTAGE_PKEY, Keys.ATTR_ABVINTAGE_ATTR_NAME_ID_ATTR_VAL_ENG_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblAttrAbvintage as(String alias) {
		return new TblAttrAbvintage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblAttrAbvintage rename(String name) {
		return new TblAttrAbvintage(name, null);
	}
}
