/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.AttrNameJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAttrName extends TableImpl<AttrNameJQR> {

	private static final long serialVersionUID = 939007022;

	/**
	 * The reference instance of <code>mic_core.attr_name</code>
	 */
	public static final TblAttrName ATTR_NAME = new TblAttrName();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AttrNameJQR> getRecordType() {
		return AttrNameJQR.class;
	}

	/**
	 * The column <code>mic_core.attr_name.attr_name_id</code>.
	 */
	public final TableField<AttrNameJQR, Short> ATTR_NAME_ID = createField("attr_name_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_name_type_id</code>.
	 */
	public final TableField<AttrNameJQR, Short> ATTR_NAME_TYPE_ID = createField("attr_name_type_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_name_rank</code>.
	 */
	public final TableField<AttrNameJQR, Short> ATTR_NAME_RANK = createField("attr_name_rank", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_name_eng</code>.
	 */
	public final TableField<AttrNameJQR, String> ATTR_NAME_ENG = createField("attr_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(127).nullable(false), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_name_chs</code>.
	 */
	public final TableField<AttrNameJQR, String> ATTR_NAME_CHS = createField("attr_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_name_cht</code>.
	 */
	public final TableField<AttrNameJQR, String> ATTR_NAME_CHT = createField("attr_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.attr_name.attr_namecode</code>.
	 */
	public final TableField<AttrNameJQR, String> ATTR_NAMECODE = createField("attr_namecode", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>mic_core.attr_name.note</code>.
	 */
	public final TableField<AttrNameJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.attr_name.seo_url</code>.
	 */
	public final TableField<AttrNameJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.attr_name.ext_url</code>.
	 */
	public final TableField<AttrNameJQR, String> EXT_URL = createField("ext_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>mic_core.attr_name</code> table reference
	 */
	public TblAttrName() {
		this("attr_name", null);
	}

	/**
	 * Create an aliased <code>mic_core.attr_name</code> table reference
	 */
	public TblAttrName(String alias) {
		this(alias, ATTR_NAME);
	}

	private TblAttrName(String alias, Table<AttrNameJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblAttrName(String alias, Table<AttrNameJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AttrNameJQR> getPrimaryKey() {
		return Keys.ATTR_NAME_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AttrNameJQR>> getKeys() {
		return Arrays.<UniqueKey<AttrNameJQR>>asList(Keys.ATTR_NAME_PKEY, Keys.ATTR_NAME_ATTR_NAME_ENG_KEY, Keys.ATTR_NAME_ATTR_NAMECODE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblAttrName as(String alias) {
		return new TblAttrName(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblAttrName rename(String name) {
		return new TblAttrName(name, null);
	}
}
