/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.AtagAbnoteJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAtagAbnote extends TableImpl<AtagAbnoteJQR> {

	private static final long serialVersionUID = -839732412;

	/**
	 * The reference instance of <code>mic_core.atag_abnote</code>
	 */
	public static final TblAtagAbnote ATAG_ABNOTE = new TblAtagAbnote();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AtagAbnoteJQR> getRecordType() {
		return AtagAbnoteJQR.class;
	}

	/**
	 * The column <code>mic_core.atag_abnote.atag_id</code>.
	 */
	public final TableField<AtagAbnoteJQR, Long> ATAG_ID = createField("atag_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.atag_abnote.atag_value</code>.
	 */
	public final TableField<AtagAbnoteJQR, String> ATAG_VALUE = createField("atag_value", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>mic_core.atag_abnote.seo_url</code>.
	 */
	public final TableField<AtagAbnoteJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.atag_abnote.last_upd_mictime</code>.
	 */
	public final TableField<AtagAbnoteJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.atag_abnote</code> table reference
	 */
	public TblAtagAbnote() {
		this("atag_abnote", null);
	}

	/**
	 * Create an aliased <code>mic_core.atag_abnote</code> table reference
	 */
	public TblAtagAbnote(String alias) {
		this(alias, ATAG_ABNOTE);
	}

	private TblAtagAbnote(String alias, Table<AtagAbnoteJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblAtagAbnote(String alias, Table<AtagAbnoteJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AtagAbnoteJQR, Long> getIdentity() {
		return Keys.IDENTITY_ATAG_ABNOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AtagAbnoteJQR> getPrimaryKey() {
		return Keys.ATAG_ABNOTE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AtagAbnoteJQR>> getKeys() {
		return Arrays.<UniqueKey<AtagAbnoteJQR>>asList(Keys.ATAG_ABNOTE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblAtagAbnote as(String alias) {
		return new TblAtagAbnote(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblAtagAbnote rename(String name) {
		return new TblAtagAbnote(name, null);
	}
}
