/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.CityJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCity extends TableImpl<CityJQR> {

	private static final long serialVersionUID = -765231797;

	/**
	 * The reference instance of <code>mic_core.city</code>
	 */
	public static final TblCity CITY = new TblCity();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CityJQR> getRecordType() {
		return CityJQR.class;
	}

	/**
	 * The column <code>mic_core.city.city_id</code>.
	 */
	public final TableField<CityJQR, Integer> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mic_core.city.city_name_eng</code>.
	 */
	public final TableField<CityJQR, String> CITY_NAME_ENG = createField("city_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mic_core.city.city_name_chs</code>.
	 */
	public final TableField<CityJQR, String> CITY_NAME_CHS = createField("city_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.city.city_name_cht</code>.
	 */
	public final TableField<CityJQR, String> CITY_NAME_CHT = createField("city_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.city.rank</code>.
	 */
	public final TableField<CityJQR, Short> RANK = createField("rank", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.city.country_id</code>.
	 */
	public final TableField<CityJQR, Short> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.city</code> table reference
	 */
	public TblCity() {
		this("city", null);
	}

	/**
	 * Create an aliased <code>mic_core.city</code> table reference
	 */
	public TblCity(String alias) {
		this(alias, CITY);
	}

	private TblCity(String alias, Table<CityJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblCity(String alias, Table<CityJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CityJQR> getPrimaryKey() {
		return Keys.CITY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CityJQR>> getKeys() {
		return Arrays.<UniqueKey<CityJQR>>asList(Keys.CITY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblCity as(String alias) {
		return new TblCity(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblCity rename(String name) {
		return new TblCity(name, null);
	}
}
