/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserProfileJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserProfile extends TableImpl<UserProfileJQR> {

	private static final long serialVersionUID = -377801588;

	/**
	 * The reference instance of <code>mic_core.user_profile</code>
	 */
	public static final TblUserProfile USER_PROFILE = new TblUserProfile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserProfileJQR> getRecordType() {
		return UserProfileJQR.class;
	}

	/**
	 * The column <code>mic_core.user_profile.user_id</code>.
	 */
	public final TableField<UserProfileJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_profile.dob</code>.
	 */
	public final TableField<UserProfileJQR, Date> DOB = createField("dob", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>mic_core.user_profile.decadob</code>.
	 */
	public final TableField<UserProfileJQR, Short> DECADOB = createField("decadob", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>mic_core.user_profile.sex</code>.
	 */
	public final TableField<UserProfileJQR, Short> SEX = createField("sex", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>mic_core.user_profile.toast_line</code>.
	 */
	public final TableField<UserProfileJQR, String> TOAST_LINE = createField("toast_line", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_profile.about_me</code>.
	 */
	public final TableField<UserProfileJQR, String> ABOUT_ME = createField("about_me", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_profile.email_me</code>.
	 */
	public final TableField<UserProfileJQR, String> EMAIL_ME = createField("email_me", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_profile.url_me</code>.
	 */
	public final TableField<UserProfileJQR, String> URL_ME = createField("url_me", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_profile.profile_banner</code>.
	 */
	public final TableField<UserProfileJQR, UUID> PROFILE_BANNER = createField("profile_banner", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.user_profile.city_id</code>.
	 */
	public final TableField<UserProfileJQR, Integer> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>mic_core.user_profile.signup_date</code>.
	 */
	public final TableField<UserProfileJQR, Date> SIGNUP_DATE = createField("signup_date", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_profile.signup_mictime</code>.
	 */
	public final TableField<UserProfileJQR, Integer> SIGNUP_MICTIME = createField("signup_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_profile.last_upd_mictime</code>.
	 */
	public final TableField<UserProfileJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_profile.signup_comp</code>.
	 */
	public final TableField<UserProfileJQR, Boolean> SIGNUP_COMP = createField("signup_comp", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_profile</code> table reference
	 */
	public TblUserProfile() {
		this("user_profile", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_profile</code> table reference
	 */
	public TblUserProfile(String alias) {
		this(alias, USER_PROFILE);
	}

	private TblUserProfile(String alias, Table<UserProfileJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserProfile(String alias, Table<UserProfileJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserProfileJQR> getPrimaryKey() {
		return Keys.USER_PROFILE_PKEY1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserProfileJQR>> getKeys() {
		return Arrays.<UniqueKey<UserProfileJQR>>asList(Keys.USER_PROFILE_PKEY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserProfile as(String alias) {
		return new TblUserProfile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserProfile rename(String name) {
		return new TblUserProfile(name, null);
	}
}
