/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserCellarJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserCellar extends TableImpl<UserCellarJQR> {

	private static final long serialVersionUID = 1335454915;

	/**
	 * The reference instance of <code>mic_core.user_cellar</code>
	 */
	public static final TblUserCellar USER_CELLAR = new TblUserCellar();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserCellarJQR> getRecordType() {
		return UserCellarJQR.class;
	}

	/**
	 * The column <code>mic_core.user_cellar.user_id</code>.
	 */
	public final TableField<UserCellarJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_cellar.wine_id</code>.
	 */
	public final TableField<UserCellarJQR, Long> WINE_ID = createField("wine_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_cellar.vintage_tag</code>.
	 */
	public final TableField<UserCellarJQR, Short> VINTAGE_TAG = createField("vintage_tag", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_cellar.quantity</code>.
	 */
	public final TableField<UserCellarJQR, Integer> QUANTITY = createField("quantity", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_cellar.note</code>.
	 */
	public final TableField<UserCellarJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_cellar.wine_img</code>.
	 */
	public final TableField<UserCellarJQR, UUID> WINE_IMG = createField("wine_img", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.user_cellar.last_upd_mictime</code>.
	 */
	public final TableField<UserCellarJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_cellar</code> table reference
	 */
	public TblUserCellar() {
		this("user_cellar", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_cellar</code> table reference
	 */
	public TblUserCellar(String alias) {
		this(alias, USER_CELLAR);
	}

	private TblUserCellar(String alias, Table<UserCellarJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserCellar(String alias, Table<UserCellarJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserCellarJQR> getPrimaryKey() {
		return Keys.USER_CELLAR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserCellarJQR>> getKeys() {
		return Arrays.<UniqueKey<UserCellarJQR>>asList(Keys.USER_CELLAR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserCellar as(String alias) {
		return new TblUserCellar(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserCellar rename(String name) {
		return new TblUserCellar(name, null);
	}
}
