/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserCountryJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserCountry extends TableImpl<UserCountryJQR> {

	private static final long serialVersionUID = 1991580601;

	/**
	 * The reference instance of <code>mic_core.user_country</code>
	 */
	public static final TblUserCountry USER_COUNTRY = new TblUserCountry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserCountryJQR> getRecordType() {
		return UserCountryJQR.class;
	}

	/**
	 * The column <code>mic_core.user_country.country_id</code>.
	 */
	public final TableField<UserCountryJQR, Short> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_country.country_code</code>.
	 */
	public final TableField<UserCountryJQR, String> COUNTRY_CODE = createField("country_code", org.jooq.impl.SQLDataType.CHAR.length(3), this, "");

	/**
	 * The column <code>mic_core.user_country.country_name_eng</code>.
	 */
	public final TableField<UserCountryJQR, String> COUNTRY_NAME_ENG = createField("country_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(127), this, "");

	/**
	 * The column <code>mic_core.user_country.country_name_chs</code>.
	 */
	public final TableField<UserCountryJQR, String> COUNTRY_NAME_CHS = createField("country_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.user_country.country_name_cht</code>.
	 */
	public final TableField<UserCountryJQR, String> COUNTRY_NAME_CHT = createField("country_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.user_country.rank</code>.
	 */
	public final TableField<UserCountryJQR, Short> RANK = createField("rank", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_country</code> table reference
	 */
	public TblUserCountry() {
		this("user_country", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_country</code> table reference
	 */
	public TblUserCountry(String alias) {
		this(alias, USER_COUNTRY);
	}

	private TblUserCountry(String alias, Table<UserCountryJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserCountry(String alias, Table<UserCountryJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserCountryJQR> getPrimaryKey() {
		return Keys.USER_COUNTRY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserCountryJQR>> getKeys() {
		return Arrays.<UniqueKey<UserCountryJQR>>asList(Keys.USER_COUNTRY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserCountry as(String alias) {
		return new TblUserCountry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserCountry rename(String name) {
		return new TblUserCountry(name, null);
	}
}
