/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.UauthLastloginJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUauthLastlogin extends TableImpl<UauthLastloginJQR> {

	private static final long serialVersionUID = 1148138298;

	/**
	 * The reference instance of <code>mic_core.uauth_lastlogin</code>
	 */
	public static final TblUauthLastlogin UAUTH_LASTLOGIN = new TblUauthLastlogin();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UauthLastloginJQR> getRecordType() {
		return UauthLastloginJQR.class;
	}

	/**
	 * The column <code>mic_core.uauth_lastlogin.user_id</code>.
	 */
	public final TableField<UauthLastloginJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.uauth_lastlogin.login_date</code>.
	 */
	public final TableField<UauthLastloginJQR, Timestamp> LOGIN_DATE = createField("login_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.uauth_lastlogin</code> table reference
	 */
	public TblUauthLastlogin() {
		this("uauth_lastlogin", null);
	}

	/**
	 * Create an aliased <code>mic_core.uauth_lastlogin</code> table reference
	 */
	public TblUauthLastlogin(String alias) {
		this(alias, UAUTH_LASTLOGIN);
	}

	private TblUauthLastlogin(String alias, Table<UauthLastloginJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUauthLastlogin(String alias, Table<UauthLastloginJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUauthLastlogin as(String alias) {
		return new TblUauthLastlogin(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUauthLastlogin rename(String name) {
		return new TblUauthLastlogin(name, null);
	}
}
