/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserHeaderJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserHeader extends TableImpl<UserHeaderJQR> {

	private static final long serialVersionUID = 543308718;

	/**
	 * The reference instance of <code>mic_core.user_header</code>
	 */
	public static final TblUserHeader USER_HEADER = new TblUserHeader();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserHeaderJQR> getRecordType() {
		return UserHeaderJQR.class;
	}

	/**
	 * The column <code>mic_core.user_header.user_id</code>.
	 */
	public final TableField<UserHeaderJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_header.user_name</code>.
	 */
	public final TableField<UserHeaderJQR, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(127).nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_header.avatar_img</code>.
	 */
	public final TableField<UserHeaderJQR, UUID> AVATAR_IMG = createField("avatar_img", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * Create a <code>mic_core.user_header</code> table reference
	 */
	public TblUserHeader() {
		this("user_header", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_header</code> table reference
	 */
	public TblUserHeader(String alias) {
		this(alias, USER_HEADER);
	}

	private TblUserHeader(String alias, Table<UserHeaderJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserHeader(String alias, Table<UserHeaderJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserHeaderJQR> getPrimaryKey() {
		return Keys.USER_HEADER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserHeaderJQR>> getKeys() {
		return Arrays.<UniqueKey<UserHeaderJQR>>asList(Keys.USER_HEADER_PKEY, Keys.USER_HEADER_USER_NAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserHeader as(String alias) {
		return new TblUserHeader(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserHeader rename(String name) {
		return new TblUserHeader(name, null);
	}
}
