/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserFavWineJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserFavWine extends TableImpl<UserFavWineJQR> {

	private static final long serialVersionUID = -721848872;

	/**
	 * The reference instance of <code>mic_core.user_fav_wine</code>
	 */
	public static final TblUserFavWine USER_FAV_WINE = new TblUserFavWine();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserFavWineJQR> getRecordType() {
		return UserFavWineJQR.class;
	}

	/**
	 * The column <code>mic_core.user_fav_wine.user_id</code>.
	 */
	public final TableField<UserFavWineJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_fav_wine.wine_id</code>.
	 */
	public final TableField<UserFavWineJQR, Long> WINE_ID = createField("wine_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_fav_wine.vintage_tag</code>.
	 */
	public final TableField<UserFavWineJQR, Short> VINTAGE_TAG = createField("vintage_tag", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_fav_wine.is_archived</code>.
	 */
	public final TableField<UserFavWineJQR, Boolean> IS_ARCHIVED = createField("is_archived", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_fav_wine.last_upd_mictime</code>.
	 */
	public final TableField<UserFavWineJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_fav_wine</code> table reference
	 */
	public TblUserFavWine() {
		this("user_fav_wine", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_fav_wine</code> table reference
	 */
	public TblUserFavWine(String alias) {
		this(alias, USER_FAV_WINE);
	}

	private TblUserFavWine(String alias, Table<UserFavWineJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserFavWine(String alias, Table<UserFavWineJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserFavWineJQR> getPrimaryKey() {
		return Keys.USER_FAV_WINE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserFavWineJQR>> getKeys() {
		return Arrays.<UniqueKey<UserFavWineJQR>>asList(Keys.USER_FAV_WINE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserFavWine as(String alias) {
		return new TblUserFavWine(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserFavWine rename(String name) {
		return new TblUserFavWine(name, null);
	}
}
