/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserNotificationJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserNotification extends TableImpl<UserNotificationJQR> {

	private static final long serialVersionUID = -221363573;

	/**
	 * The reference instance of <code>mic_core.user_notification</code>
	 */
	public static final TblUserNotification USER_NOTIFICATION = new TblUserNotification();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserNotificationJQR> getRecordType() {
		return UserNotificationJQR.class;
	}

	/**
	 * The column <code>mic_core.user_notification.user_id</code>.
	 */
	public final TableField<UserNotificationJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_notification.entity_id</code>.
	 */
	public final TableField<UserNotificationJQR, Long> ENTITY_ID = createField("entity_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_notification.enitty_type</code>.
	 */
	public final TableField<UserNotificationJQR, String> ENITTY_TYPE = createField("enitty_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_notification.msg_body</code>.
	 */
	public final TableField<UserNotificationJQR, String> MSG_BODY = createField("msg_body", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_notification.event_mictime</code>.
	 */
	public final TableField<UserNotificationJQR, Integer> EVENT_MICTIME = createField("event_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_notification</code> table reference
	 */
	public TblUserNotification() {
		this("user_notification", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_notification</code> table reference
	 */
	public TblUserNotification(String alias) {
		this(alias, USER_NOTIFICATION);
	}

	private TblUserNotification(String alias, Table<UserNotificationJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserNotification(String alias, Table<UserNotificationJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserNotificationJQR> getPrimaryKey() {
		return Keys.USER_NOTIFICATION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserNotificationJQR>> getKeys() {
		return Arrays.<UniqueKey<UserNotificationJQR>>asList(Keys.USER_NOTIFICATION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserNotification as(String alias) {
		return new TblUserNotification(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserNotification rename(String name) {
		return new TblUserNotification(name, null);
	}
}
