/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserNoteAttrJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserNoteAttr extends TableImpl<UserNoteAttrJQR> {

	private static final long serialVersionUID = -2032425603;

	/**
	 * The reference instance of <code>mic_core.user_note_attr</code>
	 */
	public static final TblUserNoteAttr USER_NOTE_ATTR = new TblUserNoteAttr();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserNoteAttrJQR> getRecordType() {
		return UserNoteAttrJQR.class;
	}

	/**
	 * The column <code>mic_core.user_note_attr.note_id</code>.
	 */
	public final TableField<UserNoteAttrJQR, Long> NOTE_ID = createField("note_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_note_attr.attr_id</code>.
	 */
	public final TableField<UserNoteAttrJQR, Long> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_note_attr.attr_assoc_val</code>.
	 */
	public final TableField<UserNoteAttrJQR, Short> ATTR_ASSOC_VAL = createField("attr_assoc_val", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>mic_core.user_note_attr.last_upd_mictime</code>.
	 */
	public final TableField<UserNoteAttrJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_note_attr</code> table reference
	 */
	public TblUserNoteAttr() {
		this("user_note_attr", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_note_attr</code> table reference
	 */
	public TblUserNoteAttr(String alias) {
		this(alias, USER_NOTE_ATTR);
	}

	private TblUserNoteAttr(String alias, Table<UserNoteAttrJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserNoteAttr(String alias, Table<UserNoteAttrJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserNoteAttrJQR> getPrimaryKey() {
		return Keys.USER_NOTE_ATTR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserNoteAttrJQR>> getKeys() {
		return Arrays.<UniqueKey<UserNoteAttrJQR>>asList(Keys.USER_NOTE_ATTR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserNoteAttr as(String alias) {
		return new TblUserNoteAttr(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserNoteAttr rename(String name) {
		return new TblUserNoteAttr(name, null);
	}
}
