/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserUptoFolwJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserUptoFolw extends TableImpl<UserUptoFolwJQR> {

	private static final long serialVersionUID = 1188903036;

	/**
	 * The reference instance of <code>mic_core.user_upto_folw</code>
	 */
	public static final TblUserUptoFolw USER_UPTO_FOLW = new TblUserUptoFolw();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserUptoFolwJQR> getRecordType() {
		return UserUptoFolwJQR.class;
	}

	/**
	 * The column <code>mic_core.user_upto_folw.follower_id</code>.
	 */
	public final TableField<UserUptoFolwJQR, UUID> FOLLOWER_ID = createField("follower_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.user_upto_folw.following_id</code>.
	 */
	public final TableField<UserUptoFolwJQR, UUID> FOLLOWING_ID = createField("following_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.user_upto_folw.last_upd_mictime</code>.
	 */
	public final TableField<UserUptoFolwJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_upto_folw</code> table reference
	 */
	public TblUserUptoFolw() {
		this("user_upto_folw", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_upto_folw</code> table reference
	 */
	public TblUserUptoFolw(String alias) {
		this(alias, USER_UPTO_FOLW);
	}

	private TblUserUptoFolw(String alias, Table<UserUptoFolwJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserUptoFolw(String alias, Table<UserUptoFolwJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserUptoFolw as(String alias) {
		return new TblUserUptoFolw(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserUptoFolw rename(String name) {
		return new TblUserUptoFolw(name, null);
	}
}
