/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UauthSclntwJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUauthSclntw extends TableImpl<UauthSclntwJQR> {

	private static final long serialVersionUID = 785710643;

	/**
	 * The reference instance of <code>mic_core.uauth_sclntw</code>
	 */
	public static final TblUauthSclntw UAUTH_SCLNTW = new TblUauthSclntw();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UauthSclntwJQR> getRecordType() {
		return UauthSclntwJQR.class;
	}

	/**
	 * The column <code>mic_core.uauth_sclntw.user_id</code>.
	 */
	public final TableField<UauthSclntwJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_type</code>.
	 */
	public final TableField<UauthSclntwJQR, Short> SN_TYPE = createField("sn_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_userid</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_USERID = createField("sn_userid", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_token</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_TOKEN = createField("sn_token", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_name</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_NAME = createField("sn_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_firstname</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_FIRSTNAME = createField("sn_firstname", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_lastname</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_LASTNAME = createField("sn_lastname", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_gender</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_GENDER = createField("sn_gender", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_timezone</code>.
	 */
	public final TableField<UauthSclntwJQR, Short> SN_TIMEZONE = createField("sn_timezone", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_locale</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_LOCALE = createField("sn_locale", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_link</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_LINK = createField("sn_link", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_email</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_EMAIL = createField("sn_email", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_birthday</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_BIRTHDAY = createField("sn_birthday", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_about</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_ABOUT = createField("sn_about", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.sn_error</code>.
	 */
	public final TableField<UauthSclntwJQR, String> SN_ERROR = createField("sn_error", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.uauth_sclntw.last_upd_time</code>.
	 */
	public final TableField<UauthSclntwJQR, Timestamp> LAST_UPD_TIME = createField("last_upd_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.uauth_sclntw</code> table reference
	 */
	public TblUauthSclntw() {
		this("uauth_sclntw", null);
	}

	/**
	 * Create an aliased <code>mic_core.uauth_sclntw</code> table reference
	 */
	public TblUauthSclntw(String alias) {
		this(alias, UAUTH_SCLNTW);
	}

	private TblUauthSclntw(String alias, Table<UauthSclntwJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUauthSclntw(String alias, Table<UauthSclntwJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UauthSclntwJQR> getPrimaryKey() {
		return Keys.UAUTH_SCLNTW_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UauthSclntwJQR>> getKeys() {
		return Arrays.<UniqueKey<UauthSclntwJQR>>asList(Keys.UAUTH_SCLNTW_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUauthSclntw as(String alias) {
		return new TblUauthSclntw(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUauthSclntw rename(String name) {
		return new TblUauthSclntw(name, null);
	}
}
