/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.UserOccasJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblUserOccas extends TableImpl<UserOccasJQR> {

	private static final long serialVersionUID = -2004503153;

	/**
	 * The reference instance of <code>mic_core.user_occas</code>
	 */
	public static final TblUserOccas USER_OCCAS = new TblUserOccas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserOccasJQR> getRecordType() {
		return UserOccasJQR.class;
	}

	/**
	 * The column <code>mic_core.user_occas.occas_id</code>.
	 */
	public final TableField<UserOccasJQR, Long> OCCAS_ID = createField("occas_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_occas.host_user_id</code>.
	 */
	public final TableField<UserOccasJQR, UUID> HOST_USER_ID = createField("host_user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_occas.host_place_id</code>.
	 */
	public final TableField<UserOccasJQR, Long> HOST_PLACE_ID = createField("host_place_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_occas.occas_date</code>.
	 */
	public final TableField<UserOccasJQR, Date> OCCAS_DATE = createField("occas_date", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_occas.occas_tag</code>.
	 */
	public final TableField<UserOccasJQR, String> OCCAS_TAG = createField("occas_tag", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>mic_core.user_occas.is_archived</code>.
	 */
	public final TableField<UserOccasJQR, Boolean> IS_ARCHIVED = createField("is_archived", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.user_occas.seo_url</code>.
	 */
	public final TableField<UserOccasJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.user_occas.last_upd_mictime</code>.
	 */
	public final TableField<UserOccasJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.user_occas</code> table reference
	 */
	public TblUserOccas() {
		this("user_occas", null);
	}

	/**
	 * Create an aliased <code>mic_core.user_occas</code> table reference
	 */
	public TblUserOccas(String alias) {
		this(alias, USER_OCCAS);
	}

	private TblUserOccas(String alias, Table<UserOccasJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblUserOccas(String alias, Table<UserOccasJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<UserOccasJQR, Long> getIdentity() {
		return Keys.IDENTITY_USER_OCCAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserOccasJQR> getPrimaryKey() {
		return Keys.USER_OCCAS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserOccasJQR>> getKeys() {
		return Arrays.<UniqueKey<UserOccasJQR>>asList(Keys.USER_OCCAS_PKEY, Keys.USER_OCCAS_HOST_USER_ID_OCCAS_DATE_OCCAS_TAG_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblUserOccas as(String alias) {
		return new TblUserOccas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblUserOccas rename(String name) {
		return new TblUserOccas(name, null);
	}
}
