/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWine extends TableImpl<WineJQR> {

	private static final long serialVersionUID = -1812389616;

	/**
	 * The reference instance of <code>mic_core.wine</code>
	 */
	public static final TblWine WINE = new TblWine();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineJQR> getRecordType() {
		return WineJQR.class;
	}

	/**
	 * The column <code>mic_core.wine.wine_id</code>.
	 */
	public final TableField<WineJQR, Long> WINE_ID = createField("wine_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.wine.wine_type_id</code>.
	 */
	public final TableField<WineJQR, Short> WINE_TYPE_ID = createField("wine_type_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.wine.winery_id</code>.
	 */
	public final TableField<WineJQR, Long> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.wine.note</code>.
	 */
	public final TableField<WineJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.wine.wine_img</code>.
	 */
	public final TableField<WineJQR, UUID> WINE_IMG = createField("wine_img", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.wine.is_valid</code>.
	 */
	public final TableField<WineJQR, Boolean> IS_VALID = createField("is_valid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>mic_core.wine.seo_url</code>.
	 */
	public final TableField<WineJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.wine.last_upd_mictime</code>.
	 */
	public final TableField<WineJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.wine</code> table reference
	 */
	public TblWine() {
		this("wine", null);
	}

	/**
	 * Create an aliased <code>mic_core.wine</code> table reference
	 */
	public TblWine(String alias) {
		this(alias, WINE);
	}

	private TblWine(String alias, Table<WineJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWine(String alias, Table<WineJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<WineJQR, Long> getIdentity() {
		return Keys.IDENTITY_WINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineJQR> getPrimaryKey() {
		return Keys.WINE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineJQR>> getKeys() {
		return Arrays.<UniqueKey<WineJQR>>asList(Keys.WINE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWine as(String alias) {
		return new TblWine(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWine rename(String name) {
		return new TblWine(name, null);
	}
}
