/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineryFolwJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWineryFolw extends TableImpl<WineryFolwJQR> {

	private static final long serialVersionUID = 513255276;

	/**
	 * The reference instance of <code>mic_core.winery_folw</code>
	 */
	public static final TblWineryFolw WINERY_FOLW = new TblWineryFolw();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineryFolwJQR> getRecordType() {
		return WineryFolwJQR.class;
	}

	/**
	 * The column <code>mic_core.winery_folw.user_id</code>.
	 */
	public final TableField<WineryFolwJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_folw.winery_id</code>.
	 */
	public final TableField<WineryFolwJQR, Long> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_folw.last_upd_mictime</code>.
	 */
	public final TableField<WineryFolwJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.winery_folw</code> table reference
	 */
	public TblWineryFolw() {
		this("winery_folw", null);
	}

	/**
	 * Create an aliased <code>mic_core.winery_folw</code> table reference
	 */
	public TblWineryFolw(String alias) {
		this(alias, WINERY_FOLW);
	}

	private TblWineryFolw(String alias, Table<WineryFolwJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWineryFolw(String alias, Table<WineryFolwJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineryFolwJQR> getPrimaryKey() {
		return Keys.WINERY_FOLW_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineryFolwJQR>> getKeys() {
		return Arrays.<UniqueKey<WineryFolwJQR>>asList(Keys.WINERY_FOLW_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWineryFolw as(String alias) {
		return new TblWineryFolw(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWineryFolw rename(String name) {
		return new TblWineryFolw(name, null);
	}
}
