/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineryCountryJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWineryCountry extends TableImpl<WineryCountryJQR> {

	private static final long serialVersionUID = 689503213;

	/**
	 * The reference instance of <code>mic_core.winery_country</code>
	 */
	public static final TblWineryCountry WINERY_COUNTRY = new TblWineryCountry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineryCountryJQR> getRecordType() {
		return WineryCountryJQR.class;
	}

	/**
	 * The column <code>mic_core.winery_country.country_id</code>.
	 */
	public final TableField<WineryCountryJQR, Integer> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_country.country_code</code>.
	 */
	public final TableField<WineryCountryJQR, String> COUNTRY_CODE = createField("country_code", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_country.rank</code>.
	 */
	public final TableField<WineryCountryJQR, Short> RANK = createField("rank", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery_country.country_name_eng</code>.
	 */
	public final TableField<WineryCountryJQR, String> COUNTRY_NAME_ENG = createField("country_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(127).nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_country.country_name_chs</code>.
	 */
	public final TableField<WineryCountryJQR, String> COUNTRY_NAME_CHS = createField("country_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery_country.country_name_cht</code>.
	 */
	public final TableField<WineryCountryJQR, String> COUNTRY_NAME_CHT = createField("country_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery_country.note</code>.
	 */
	public final TableField<WineryCountryJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.winery_country.seo_url</code>.
	 */
	public final TableField<WineryCountryJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>mic_core.winery_country</code> table reference
	 */
	public TblWineryCountry() {
		this("winery_country", null);
	}

	/**
	 * Create an aliased <code>mic_core.winery_country</code> table reference
	 */
	public TblWineryCountry(String alias) {
		this(alias, WINERY_COUNTRY);
	}

	private TblWineryCountry(String alias, Table<WineryCountryJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWineryCountry(String alias, Table<WineryCountryJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineryCountryJQR> getPrimaryKey() {
		return Keys.WINE_COUNTRY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineryCountryJQR>> getKeys() {
		return Arrays.<UniqueKey<WineryCountryJQR>>asList(Keys.WINE_COUNTRY_PKEY, Keys.WINE_COUNTRY_COUNTRY_CODE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWineryCountry as(String alias) {
		return new TblWineryCountry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWineryCountry rename(String name) {
		return new TblWineryCountry(name, null);
	}
}
