/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineryJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWinery extends TableImpl<WineryJQR> {

	private static final long serialVersionUID = -1161523858;

	/**
	 * The reference instance of <code>mic_core.winery</code>
	 */
	public static final TblWinery WINERY = new TblWinery();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineryJQR> getRecordType() {
		return WineryJQR.class;
	}

	/**
	 * The column <code>mic_core.winery.winery_id</code>.
	 */
	public final TableField<WineryJQR, Long> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery.winery_name_usr</code>.
	 */
	public final TableField<WineryJQR, String> WINERY_NAME_USR = createField("winery_name_usr", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mic_core.winery.winery_name_eng</code>.
	 */
	public final TableField<WineryJQR, String> WINERY_NAME_ENG = createField("winery_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mic_core.winery.winery_name_chs</code>.
	 */
	public final TableField<WineryJQR, String> WINERY_NAME_CHS = createField("winery_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery.winery_name_cht</code>.
	 */
	public final TableField<WineryJQR, String> WINERY_NAME_CHT = createField("winery_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery.region_id</code>.
	 */
	public final TableField<WineryJQR, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery.region_alt_id</code>.
	 */
	public final TableField<WineryJQR, Integer> REGION_ALT_ID = createField("region_alt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery.country_id</code>.
	 */
	public final TableField<WineryJQR, Integer> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery.note</code>.
	 */
	public final TableField<WineryJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.winery.winery_img</code>.
	 */
	public final TableField<WineryJQR, UUID> WINERY_IMG = createField("winery_img", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.winery.is_valid</code>.
	 */
	public final TableField<WineryJQR, Boolean> IS_VALID = createField("is_valid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>mic_core.winery.seo_url</code>.
	 */
	public final TableField<WineryJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.winery.official_user_id</code>.
	 */
	public final TableField<WineryJQR, UUID> OFFICIAL_USER_ID = createField("official_user_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.winery.last_upd_mictime</code>.
	 */
	public final TableField<WineryJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.winery</code> table reference
	 */
	public TblWinery() {
		this("winery", null);
	}

	/**
	 * Create an aliased <code>mic_core.winery</code> table reference
	 */
	public TblWinery(String alias) {
		this(alias, WINERY);
	}

	private TblWinery(String alias, Table<WineryJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWinery(String alias, Table<WineryJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<WineryJQR, Long> getIdentity() {
		return Keys.IDENTITY_WINERY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineryJQR> getPrimaryKey() {
		return Keys.WINERY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineryJQR>> getKeys() {
		return Arrays.<UniqueKey<WineryJQR>>asList(Keys.WINERY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWinery as(String alias) {
		return new TblWinery(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWinery rename(String name) {
		return new TblWinery(name, null);
	}
}
