/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineTypeJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWineType extends TableImpl<WineTypeJQR> {

	private static final long serialVersionUID = -1897974223;

	/**
	 * The reference instance of <code>mic_core.wine_type</code>
	 */
	public static final TblWineType WINE_TYPE = new TblWineType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineTypeJQR> getRecordType() {
		return WineTypeJQR.class;
	}

	/**
	 * The column <code>mic_core.wine_type.wine_type_id</code>.
	 */
	public final TableField<WineTypeJQR, Short> WINE_TYPE_ID = createField("wine_type_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.wine_type.wine_type_name_eng</code>.
	 */
	public final TableField<WineTypeJQR, String> WINE_TYPE_NAME_ENG = createField("wine_type_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(127), this, "");

	/**
	 * The column <code>mic_core.wine_type.wine_type_name_chs</code>.
	 */
	public final TableField<WineTypeJQR, String> WINE_TYPE_NAME_CHS = createField("wine_type_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.wine_type.wine_type_name_cht</code>.
	 */
	public final TableField<WineTypeJQR, String> WINE_TYPE_NAME_CHT = createField("wine_type_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.wine_type.rank</code>.
	 */
	public final TableField<WineTypeJQR, Short> RANK = createField("rank", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.wine_type.seo_url</code>.
	 */
	public final TableField<WineTypeJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.wine_type.last_upd_mictime</code>.
	 */
	public final TableField<WineTypeJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.wine_type</code> table reference
	 */
	public TblWineType() {
		this("wine_type", null);
	}

	/**
	 * Create an aliased <code>mic_core.wine_type</code> table reference
	 */
	public TblWineType(String alias) {
		this(alias, WINE_TYPE);
	}

	private TblWineType(String alias, Table<WineTypeJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWineType(String alias, Table<WineTypeJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineTypeJQR> getPrimaryKey() {
		return Keys.WINE_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineTypeJQR>> getKeys() {
		return Arrays.<UniqueKey<WineTypeJQR>>asList(Keys.WINE_TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWineType as(String alias) {
		return new TblWineType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWineType rename(String name) {
		return new TblWineType(name, null);
	}
}
