/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineryRegionJQR;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWineryRegion extends TableImpl<WineryRegionJQR> {

	private static final long serialVersionUID = 1220180154;

	/**
	 * The reference instance of <code>mic_core.winery_region</code>
	 */
	public static final TblWineryRegion WINERY_REGION = new TblWineryRegion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineryRegionJQR> getRecordType() {
		return WineryRegionJQR.class;
	}

	/**
	 * The column <code>mic_core.winery_region.region_id</code>.
	 */
	public final TableField<WineryRegionJQR, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery_region.region_alt_id</code>.
	 */
	public final TableField<WineryRegionJQR, Integer> REGION_ALT_ID = createField("region_alt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.winery_region.country_id</code>.
	 */
	public final TableField<WineryRegionJQR, Integer> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_region.region_name_eng</code>.
	 */
	public final TableField<WineryRegionJQR, String> REGION_NAME_ENG = createField("region_name_eng", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mic_core.winery_region.region_name_chs</code>.
	 */
	public final TableField<WineryRegionJQR, String> REGION_NAME_CHS = createField("region_name_chs", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery_region.region_name_cht</code>.
	 */
	public final TableField<WineryRegionJQR, String> REGION_NAME_CHT = createField("region_name_cht", org.jooq.impl.SQLDataType.VARCHAR.length(31), this, "");

	/**
	 * The column <code>mic_core.winery_region.note</code>.
	 */
	public final TableField<WineryRegionJQR, String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.winery_region.region_img</code>.
	 */
	public final TableField<WineryRegionJQR, UUID> REGION_IMG = createField("region_img", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>mic_core.winery_region.is_valid</code>.
	 */
	public final TableField<WineryRegionJQR, Boolean> IS_VALID = createField("is_valid", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>mic_core.winery_region.seo_url</code>.
	 */
	public final TableField<WineryRegionJQR, String> SEO_URL = createField("seo_url", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>mic_core.winery_region.last_upd_mictime</code>.
	 */
	public final TableField<WineryRegionJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.winery_region</code> table reference
	 */
	public TblWineryRegion() {
		this("winery_region", null);
	}

	/**
	 * Create an aliased <code>mic_core.winery_region</code> table reference
	 */
	public TblWineryRegion(String alias) {
		this(alias, WINERY_REGION);
	}

	private TblWineryRegion(String alias, Table<WineryRegionJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWineryRegion(String alias, Table<WineryRegionJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<WineryRegionJQR, Integer> getIdentity() {
		return Keys.IDENTITY_WINERY_REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineryRegionJQR> getPrimaryKey() {
		return Keys.WINERY_REGION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineryRegionJQR>> getKeys() {
		return Arrays.<UniqueKey<WineryRegionJQR>>asList(Keys.WINERY_REGION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWineryRegion as(String alias) {
		return new TblWineryRegion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWineryRegion rename(String name) {
		return new TblWineryRegion(name, null);
	}
}
