/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import myicellar.jooq.Keys;
import myicellar.jooq.MicCore;
import myicellar.jooq.records.WineryRegionFolwJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblWineryRegionFolw extends TableImpl<WineryRegionFolwJQR> {

	private static final long serialVersionUID = -1641347832;

	/**
	 * The reference instance of <code>mic_core.winery_region_folw</code>
	 */
	public static final TblWineryRegionFolw WINERY_REGION_FOLW = new TblWineryRegionFolw();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WineryRegionFolwJQR> getRecordType() {
		return WineryRegionFolwJQR.class;
	}

	/**
	 * The column <code>mic_core.winery_region_folw.user_id</code>.
	 */
	public final TableField<WineryRegionFolwJQR, UUID> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_region_folw.region_id</code>.
	 */
	public final TableField<WineryRegionFolwJQR, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mic_core.winery_region_folw.last_upd_mictime</code>.
	 */
	public final TableField<WineryRegionFolwJQR, Integer> LAST_UPD_MICTIME = createField("last_upd_mictime", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mic_core.winery_region_folw</code> table reference
	 */
	public TblWineryRegionFolw() {
		this("winery_region_folw", null);
	}

	/**
	 * Create an aliased <code>mic_core.winery_region_folw</code> table reference
	 */
	public TblWineryRegionFolw(String alias) {
		this(alias, WINERY_REGION_FOLW);
	}

	private TblWineryRegionFolw(String alias, Table<WineryRegionFolwJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblWineryRegionFolw(String alias, Table<WineryRegionFolwJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<WineryRegionFolwJQR> getPrimaryKey() {
		return Keys.WINERY_REGION_FOLW_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<WineryRegionFolwJQR>> getKeys() {
		return Arrays.<UniqueKey<WineryRegionFolwJQR>>asList(Keys.WINERY_REGION_FOLW_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblWineryRegionFolw as(String alias) {
		return new TblWineryRegionFolw(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblWineryRegionFolw rename(String name) {
		return new TblWineryRegionFolw(name, null);
	}
}
