/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyWineryRegionJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyWineryRegion extends TableImpl<ZyWineryRegionJQR> {

	private static final long serialVersionUID = -255121981;

	/**
	 * The reference instance of <code>mic_core.zy_winery_region</code>
	 */
	public static final TblZyWineryRegion ZY_WINERY_REGION = new TblZyWineryRegion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyWineryRegionJQR> getRecordType() {
		return ZyWineryRegionJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_winery_region.region_id</code>.
	 */
	public final TableField<ZyWineryRegionJQR, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_winery_region.action_type</code>.
	 */
	public final TableField<ZyWineryRegionJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_winery_region.action_time</code>.
	 */
	public final TableField<ZyWineryRegionJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_winery_region.action_by</code>.
	 */
	public final TableField<ZyWineryRegionJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_winery_region</code> table reference
	 */
	public TblZyWineryRegion() {
		this("zy_winery_region", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_winery_region</code> table reference
	 */
	public TblZyWineryRegion(String alias) {
		this(alias, ZY_WINERY_REGION);
	}

	private TblZyWineryRegion(String alias, Table<ZyWineryRegionJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyWineryRegion(String alias, Table<ZyWineryRegionJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyWineryRegion as(String alias) {
		return new TblZyWineryRegion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyWineryRegion rename(String name) {
		return new TblZyWineryRegion(name, null);
	}
}
