/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyUserOccasJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyUserOccas extends TableImpl<ZyUserOccasJQR> {

	private static final long serialVersionUID = -311382199;

	/**
	 * The reference instance of <code>mic_core.zy_user_occas</code>
	 */
	public static final TblZyUserOccas ZY_USER_OCCAS = new TblZyUserOccas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyUserOccasJQR> getRecordType() {
		return ZyUserOccasJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_user_occas.occas_id</code>.
	 */
	public final TableField<ZyUserOccasJQR, Long> OCCAS_ID = createField("occas_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_user_occas.action_type</code>.
	 */
	public final TableField<ZyUserOccasJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_user_occas.action_time</code>.
	 */
	public final TableField<ZyUserOccasJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_user_occas.action_by</code>.
	 */
	public final TableField<ZyUserOccasJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_user_occas</code> table reference
	 */
	public TblZyUserOccas() {
		this("zy_user_occas", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_user_occas</code> table reference
	 */
	public TblZyUserOccas(String alias) {
		this(alias, ZY_USER_OCCAS);
	}

	private TblZyUserOccas(String alias, Table<ZyUserOccasJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyUserOccas(String alias, Table<ZyUserOccasJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyUserOccas as(String alias) {
		return new TblZyUserOccas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyUserOccas rename(String name) {
		return new TblZyUserOccas(name, null);
	}
}
