/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyAttrAbvintageJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyAttrAbvintage extends TableImpl<ZyAttrAbvintageJQR> {

	private static final long serialVersionUID = -2002359798;

	/**
	 * The reference instance of <code>mic_core.zy_attr_abvintage</code>
	 */
	public static final TblZyAttrAbvintage ZY_ATTR_ABVINTAGE = new TblZyAttrAbvintage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyAttrAbvintageJQR> getRecordType() {
		return ZyAttrAbvintageJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_attr_abvintage.attr_id</code>.
	 */
	public final TableField<ZyAttrAbvintageJQR, Long> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abvintage.action_name_id</code>.
	 */
	public final TableField<ZyAttrAbvintageJQR, Short> ACTION_NAME_ID = createField("action_name_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abvintage.action_time</code>.
	 */
	public final TableField<ZyAttrAbvintageJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abvintage.action_by</code>.
	 */
	public final TableField<ZyAttrAbvintageJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_attr_abvintage</code> table reference
	 */
	public TblZyAttrAbvintage() {
		this("zy_attr_abvintage", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_attr_abvintage</code> table reference
	 */
	public TblZyAttrAbvintage(String alias) {
		this(alias, ZY_ATTR_ABVINTAGE);
	}

	private TblZyAttrAbvintage(String alias, Table<ZyAttrAbvintageJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyAttrAbvintage(String alias, Table<ZyAttrAbvintageJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyAttrAbvintage as(String alias) {
		return new TblZyAttrAbvintage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyAttrAbvintage rename(String name) {
		return new TblZyAttrAbvintage(name, null);
	}
}
