/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyUserNoteJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyUserNote extends TableImpl<ZyUserNoteJQR> {

	private static final long serialVersionUID = -1288586299;

	/**
	 * The reference instance of <code>mic_core.zy_user_note</code>
	 */
	public static final TblZyUserNote ZY_USER_NOTE = new TblZyUserNote();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyUserNoteJQR> getRecordType() {
		return ZyUserNoteJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_user_note.note_id</code>.
	 */
	public final TableField<ZyUserNoteJQR, Long> NOTE_ID = createField("note_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_user_note.action_type</code>.
	 */
	public final TableField<ZyUserNoteJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_user_note.action_time</code>.
	 */
	public final TableField<ZyUserNoteJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_user_note.action_by</code>.
	 */
	public final TableField<ZyUserNoteJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_user_note</code> table reference
	 */
	public TblZyUserNote() {
		this("zy_user_note", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_user_note</code> table reference
	 */
	public TblZyUserNote(String alias) {
		this(alias, ZY_USER_NOTE);
	}

	private TblZyUserNote(String alias, Table<ZyUserNoteJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyUserNote(String alias, Table<ZyUserNoteJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyUserNote as(String alias) {
		return new TblZyUserNote(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyUserNote rename(String name) {
		return new TblZyUserNote(name, null);
	}
}
