/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyWineNameJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyWineName extends TableImpl<ZyWineNameJQR> {

	private static final long serialVersionUID = 1323978399;

	/**
	 * The reference instance of <code>mic_core.zy_wine_name</code>
	 */
	public static final TblZyWineName ZY_WINE_NAME = new TblZyWineName();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyWineNameJQR> getRecordType() {
		return ZyWineNameJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_wine_name.wine_name_id</code>.
	 */
	public final TableField<ZyWineNameJQR, Long> WINE_NAME_ID = createField("wine_name_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_wine_name.action_type</code>.
	 */
	public final TableField<ZyWineNameJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_wine_name.action_time</code>.
	 */
	public final TableField<ZyWineNameJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_wine_name.action_by</code>.
	 */
	public final TableField<ZyWineNameJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * Create a <code>mic_core.zy_wine_name</code> table reference
	 */
	public TblZyWineName() {
		this("zy_wine_name", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_wine_name</code> table reference
	 */
	public TblZyWineName(String alias) {
		this(alias, ZY_WINE_NAME);
	}

	private TblZyWineName(String alias, Table<ZyWineNameJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyWineName(String alias, Table<ZyWineNameJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyWineName as(String alias) {
		return new TblZyWineName(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyWineName rename(String name) {
		return new TblZyWineName(name, null);
	}
}
