/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyVintageJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyVintage extends TableImpl<ZyVintageJQR> {

	private static final long serialVersionUID = -797190149;

	/**
	 * The reference instance of <code>mic_core.zy_vintage</code>
	 */
	public static final TblZyVintage ZY_VINTAGE = new TblZyVintage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyVintageJQR> getRecordType() {
		return ZyVintageJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_vintage.wine_id</code>.
	 */
	public final TableField<ZyVintageJQR, Long> WINE_ID = createField("wine_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_vintage.vintage_tag</code>.
	 */
	public final TableField<ZyVintageJQR, Short> VINTAGE_TAG = createField("vintage_tag", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_vintage.action_type</code>.
	 */
	public final TableField<ZyVintageJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_vintage.action_time</code>.
	 */
	public final TableField<ZyVintageJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_vintage.action_by</code>.
	 */
	public final TableField<ZyVintageJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_vintage</code> table reference
	 */
	public TblZyVintage() {
		this("zy_vintage", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_vintage</code> table reference
	 */
	public TblZyVintage(String alias) {
		this(alias, ZY_VINTAGE);
	}

	private TblZyVintage(String alias, Table<ZyVintageJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyVintage(String alias, Table<ZyVintageJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyVintage as(String alias) {
		return new TblZyVintage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyVintage rename(String name) {
		return new TblZyVintage(name, null);
	}
}
