/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyWineryJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyWinery extends TableImpl<ZyWineryJQR> {

	private static final long serialVersionUID = -2006250218;

	/**
	 * The reference instance of <code>mic_core.zy_winery</code>
	 */
	public static final TblZyWinery ZY_WINERY = new TblZyWinery();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyWineryJQR> getRecordType() {
		return ZyWineryJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_winery.winery_id</code>.
	 */
	public final TableField<ZyWineryJQR, Long> WINERY_ID = createField("winery_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_winery.action_type</code>.
	 */
	public final TableField<ZyWineryJQR, Short> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_winery.action_time</code>.
	 */
	public final TableField<ZyWineryJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_winery.action_by</code>.
	 */
	public final TableField<ZyWineryJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_winery</code> table reference
	 */
	public TblZyWinery() {
		this("zy_winery", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_winery</code> table reference
	 */
	public TblZyWinery(String alias) {
		this(alias, ZY_WINERY);
	}

	private TblZyWinery(String alias, Table<ZyWineryJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyWinery(String alias, Table<ZyWineryJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyWinery as(String alias) {
		return new TblZyWinery(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyWinery rename(String name) {
		return new TblZyWinery(name, null);
	}
}
