/**
 * This class is generated by jOOQ
 */
package myicellar.jooq.tables;


import java.sql.Timestamp;
import java.util.UUID;

import myicellar.jooq.MicCore;
import myicellar.jooq.records.ZyAttrAbnoteJQR;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblZyAttrAbnote extends TableImpl<ZyAttrAbnoteJQR> {

	private static final long serialVersionUID = -385068938;

	/**
	 * The reference instance of <code>mic_core.zy_attr_abnote</code>
	 */
	public static final TblZyAttrAbnote ZY_ATTR_ABNOTE = new TblZyAttrAbnote();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ZyAttrAbnoteJQR> getRecordType() {
		return ZyAttrAbnoteJQR.class;
	}

	/**
	 * The column <code>mic_core.zy_attr_abnote.attr_id</code>.
	 */
	public final TableField<ZyAttrAbnoteJQR, Long> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abnote.action_name_id</code>.
	 */
	public final TableField<ZyAttrAbnoteJQR, Short> ACTION_NAME_ID = createField("action_name_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abnote.action_time</code>.
	 */
	public final TableField<ZyAttrAbnoteJQR, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mic_core.zy_attr_abnote.action_by</code>.
	 */
	public final TableField<ZyAttrAbnoteJQR, UUID> ACTION_BY = createField("action_by", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>mic_core.zy_attr_abnote</code> table reference
	 */
	public TblZyAttrAbnote() {
		this("zy_attr_abnote", null);
	}

	/**
	 * Create an aliased <code>mic_core.zy_attr_abnote</code> table reference
	 */
	public TblZyAttrAbnote(String alias) {
		this(alias, ZY_ATTR_ABNOTE);
	}

	private TblZyAttrAbnote(String alias, Table<ZyAttrAbnoteJQR> aliased) {
		this(alias, aliased, null);
	}

	private TblZyAttrAbnote(String alias, Table<ZyAttrAbnoteJQR> aliased, Field<?>[] parameters) {
		super(alias, MicCore.MIC_CORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TblZyAttrAbnote as(String alias) {
		return new TblZyAttrAbnote(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TblZyAttrAbnote rename(String name) {
		return new TblZyAttrAbnote(name, null);
	}
}
